SaladTechnologies/salad-applications

netlify.toml
packages/web-app/.env

@dsarfati and @thedigitaldesign, are there any other configuration values (or hardcoded constants) that need to get updated?
With the new network topology, all traffic to `https://app.salad.io` will get routed to the load balancer. The load balancer will then route traffic as follows (in order):
> 1. https://app.salad.io/api/* -> API
> 2. https://app.salad.io/* -> Application
The `app-api.salad.io` subdomain will be retired.

Use load balanced API to eliminate CORS pre-flight requests DEV-217

---

packages/web-app/src/App.tsx
packages/web-app/src/Store.ts
packages/web-app/src/modules/machine/MachineStore.ts
packages/web-app/src/modules/machine/NativeStore.ts
packages/web-app/src/modules/profile-views/UserStatsSummaryContainer.ts
packages/web-app/src/modules/profile-views/components/ProfileViews.stories.tsx
packages/web-app/src/modules/profile-views/components/UserStatsSummary.tsx

- Added in an interval that hits loadMachineInfo until we have machineInfo
-- This is a ugly, but is needed to ensure we have set machineInfo.
- Found that the earningRate was tied to this issue. Without machineInfo we couldn't get the user and their earning rate. On refresh we would fetch it, but now it is updated when we get machineInfo from the setInterval
- Added in 'Loading' under Earning Rate while we are fetching machineInfo. Moved the logic off of the .tsx and onto the store

DEV-490 & DEV-488

---

packages/web-app/src/modules/referral/ReferralStore.ts

Catch known referral error status codes, preventing Sentry from logging this as an error

Catch known referral 404s

---

packages/web-app/src/modules/reward/utils.ts
packages/web-app/src/modules/settings-views/referral-views/components/CurrentReferralPanel.tsx
packages/web-app/src/modules/settings-views/referral-views/components/ReferralCodeEntryComponent.tsx

We were not checking to see if the tags were undefined/ null, so when mapping the Tags, it would attempt to map null and break the carousel. We are now checking to see if tags are null/ undefined and not mapping if so.

Fixed null Breaking Reward List DEV-643

---

packages/desktop-app/src/salad-bowl/Plugin.ts
packages/web-app/src/modules/salad-bowl/definitions/getClaymoreDefinition.ts
packages/web-app/src/modules/salad-bowl/definitions/getGminerBeamV2Definition.ts
packages/web-app/src/modules/salad-bowl/definitions/getGminerEthDefinition.ts

This adds fallback pools when using Claymore. This also reduces the time it takes for pool failures to be detected when using Gminer.

Add Claymore fallback pools and improve fast failure scenarios DEV-915

---

packages/web-app/package.json
packages/web-app/yarn.lock

This fixes an issue running the webpack dev server that throws the following error:
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
at validateString (internal/validators.js:113:11)
at Object.join (path.js:375:7)
[...]
```

Update react-scripts npm dependency DEV-1154

---

netlify.toml

Updated the netlify deploy previews to point to the test auth0 tenant. It had been pointed back to prod when the test env was down. 
https://github.com/SaladTechnologies/salad-applications/pull/333

Updated netlify config to point previews to test auth0 tenant

---

packages/web-app/src/modules/salad-bowl/PluginDefinitionFactory.ts

This fixes a missing 4GB VRAM check, and it moves the Ethermine plugin to the end of the fallback list due to an unknown EPERM issue.

Filter Ethash plugins for lower-end GPUs

---

packages/web-app/src/modules/earn-views/components/Offerwall.tsx

Currently Salad just refers to the image as "Example Offers", but the interfaces vary between offerwall to offerwall.

Clarify example offerwall image

---

packages/web-app/src/modules/salad-bowl/PluginDefinitionFactory.ts
packages/web-app/src/modules/salad-bowl/definitions/getCCMinerLyra2REv3Definition.ts
packages/web-app/src/modules/salad-bowl/definitions/getCCMinerX16RDefinition.ts
packages/web-app/src/modules/salad-bowl/definitions/getClaymoreEthashBitflyDefinition.ts
packages/web-app/src/modules/salad-bowl/definitions/getClaymoreEthashDefinition.ts
packages/web-app/src/modules/salad-bowl/definitions/getClaymoreEthashNanopoolDefinition.ts
packages/web-app/src/modules/salad-bowl/definitions/getGminerBeamBitflyDefinition.ts
packages/web-app/src/modules/salad-bowl/definitions/getGminerBeamHashIIDefinition.ts
packages/web-app/src/modules/salad-bowl/definitions/getGminerCuckARoom29Definition.ts
packages/web-app/src/modules/salad-bowl/definitions/getGminerZHashDefinition.ts
packages/web-app/src/modules/salad-bowl/definitions/getPhoenixMinerEthashBitflyDefinition.ts
packages/web-app/src/modules/salad-bowl/definitions/getPhoenixMinerEthashDefinition.ts
packages/web-app/src/modules/salad-bowl/definitions/getPhoenixMinerEthashNanopoolDefinition.ts
packages/web-app/src/modules/salad-bowl/definitions/getXMRigRandomXCUDADefinition.ts
packages/web-app/src/modules/salad-bowl/definitions/getXMRigRandomXOpenCLDefinition.ts

This should result in users downloading less redundant miners from Salad. This should also result in some users seeing their clients transition from the initializing to running state much faster.

Updated all plugin definitions to consolidate names and check hashrates

---

packages/web-app/src/index.tsx

A benign error message... ignoring it to reduce the noise in Sentry.

Ignore ResizeObserver error

---

packages/web-app/src/modules/machine/NativeStore.ts

A lot of technical support requests follow the pattern of asking a user to confirm their GPU make & model followed up by asking for a copy of the application log file. This is an attempt to speed up the process, get both pieces of information at once.

Log system information

---

packages/web-app/src/modules/machine/NativeStore.ts
packages/web-app/src/modules/settings-views/windows-settings-views/WindowsSettingsContainer.ts
packages/web-app/src/modules/settings-views/windows-settings-views/components/WindowsSettings.tsx

This fixes restoring the persisted "Close to Tray" option after Salad is closed & reopened.

Restore persisted "Close to Tray" options

---

packages/web-app/src/modules/salad-bowl/definitions/getTrexRavencoinNiceHashDefinition.ts

This removes an invalid `-w 0` command line argument that was being passed to T-Rex. The invalid argument caused T-Rex to print its help information and exit.

Remove invalid T-Rex command line argument

---

packages/web-app/src/modules/salad-bowl/definitions/getTrexRavencoinNiceHashDefinition.ts

This adds a couple of command line arguments to the T-Rex plugin definition that should cause it to gracefully shutdown instead of becoming stuck in an infinite retry loop.

Use T-Rex graceful shutdown options

---

packages/desktop-app/src/icons.ts
packages/desktop-app/src/main.ts

As of https://trello.com/c/bz057Sg7/1-icon-compatibility
`icons.ts` uses the `process` module to check for platform. `.ico` files are used on win32 and `.png` for linux/darwin.

Move icon path definitions out from main.ts into icons.ts.

---

packages/desktop-app/src/preload.js
packages/web-app/src/modules/machine/NativeStore.ts

Replaces the `electron` value injected in preload.js with the actual Node.js platform value (i.e. `darwin`, `linux`, `win32`).

Inject Node.js platform name in preload.js (i.e. darwin, linux, win32)

---

packages/desktop-app/src/salad-bowl/Plugin.ts

Doing just this.process.kill() is not enough on linux to end miner process; use pkill to kill the process.

Add proper plugin stopping for linux platforms

---

packages/web-app/src/modules/analytics/AnalyticsStore.ts

The "Mining Error" event is sending too many AV errors to MixPanel, most of which are currently expected. This silences the AV errors to reduce the noise.

Reduce AV error noise in MixPanel

---

packages/web-app/src/modules/salad-bowl/definitions/linux/phoenixminer-ethash.tsx

add the `-log 0` arguments to explicitly disable logging.
without this, PhoenixMiner is logging to the users home directory

Explicitly disable PhoenixMiner logging on linux

---

packages/desktop-app/src/main.ts

Replaces the Electron-standard macOS menu items with Salad-specific menu items. Notably, this links to the Salad websites and hides developer tools.

Add Salad links to macOS menu

---

packages/desktop-app/build/entitlements.mac.plist
packages/desktop-app/build/notarize.js
packages/desktop-app/electron-builder.json
packages/desktop-app/package.json
packages/desktop-app/yarn.lock

This adds some automation magic to sign the macOS app build with the Salad Developer ID certificate.

Notarize macOS package

---

packages/web-app/src/modules/salad-bowl/definitions/macos/xmrig-kawpow.tsx
packages/web-app/src/modules/salad-bowl/definitions/macos/xmrig-randomx.tsx

Temporarily disables GPU mining on macOS. We just need more time to test. Currently, there are a lot of compatibility issues on our test machines.

Disable GPU mining on macOS

---

packages/web-app/src/modules/xp-views/components/Pantry.tsx
packages/web-app/src/modules/xp-views/components/SlicedVeggie.tsx

The recent webpack loader/CRA updates changed the type of the module returned by a dynamic `require` to align with ES6 modules. The veggie URLs are now the `default` export of the module.

Fix veggie module imports

---

packages/web-app/public/index.html
packages/web-app/src/Store.ts
packages/web-app/src/modules/zendesk/Zendesk.ts
packages/web-app/src/modules/zendesk/index.ts
packages/web-app/src/modules/zendesk/models/ZendeskWebWidget.ts
packages/web-app/src/modules/zendesk/models/index.ts

Adds authentication callback to Zendesk web widget settings by passing along auth user JWT. This also moves the initialization of the Zandesk snippet from `index.html` to `Store.ts`.

Add Zendesk authentication

---

packages/web-app/src/Store.ts
packages/web-app/src/modules/versions/VersionStore.ts

1. Removes logic that triggers auto-reload of app on new releases. 
2. Moves call of `checkDesktopVersion` from `startVersionChecks` to initialization of `VersionStore` class.

Disabled auto-reload on change of version

---

packages/web-app/src/modules/settings-views/SettingsContainer.ts
packages/web-app/src/modules/versions/VersionStore.ts

1. Only shows LogOut button on Settings page if user is Authenticated
2. Only check desktop version if on the native app

Desktop version check and LogOut button fixes

---

packages/web-app/src/modules/earn-views/components/EarningChart.tsx

Fixes overlap of chart by removing determined height for chart. To also prevent jumping of chart from pushing content down, just hiding visibility of text instead of removing element from DOM completely.
Previously, the text told the user that they have "no earning history", but that might only be the case for the zoom level they are in. So I updated that messaging to be dynamic based on zoom level.
Also adds a check to prevent the earning range tool tip from showing is there is no earning history for the current zoom level.

Fix chart overlapping into pantry list after changing zoom

---

packages/web-app/src/modules/earn-views/components/EarningChart.tsx

The minHeight property was not working on mobile, so I changed the chart back to absolute height.

Fix chart not showing up on mobile

---

packages/web-app/public/index.html

It's all in the title. We'll get some usage analytics in aggregate form, respecting users' privacy. More details are available on [Cloudflare's website](https://www.cloudflare.com/web-analytics/).

Add Cloudflare's privacy-focused web analytics

---

packages/desktop-app/.env
packages/desktop-app/.env.development
packages/desktop-app/.gitignore
packages/desktop-app/package.json
packages/desktop-app/src/config.ts
packages/desktop-app/src/main.ts
packages/desktop-app/yarn.lock

Support for `.env` files was already available in `electron-webpack`. It is configured to behave similarly to `create-react-app`, including variable expansion. The files loaded include:
- `.env`
- `.env.local`
- `.env.{NODE_ENV}`
- `.env.{NODE_ENV}.local`

Refactor config to .env files

---

packages/desktop-app/build/license_en.txt
packages/desktop-app/build/opensuse.patch
packages/desktop-app/electron-builder.json

Fixes the Ubuntu, Fedora, and openSUSE dependencies. `electron-builder` doesn't allow for two different `rpm` package definitions. This includes a `.patch` file that changes the `rpm` package dependencies from those required for Fedora (default) to those required for openSUSE.

Fix Linux package dependencies

---

packages/web-app/src/modules/analytics/AnalyticsStore.ts
packages/web-app/src/modules/reward/RewardStore.ts

Currently adding an alternative tracking event to try and catch redemptions that are taking time to be processed with G2A.

Add tracking event for g2a redemptions being processed

---

packages/web-app/src/modules/reward-views/pages/MainStorefrontPage.tsx
packages/web-app/src/modules/reward/RewardStore.ts

The hard-coded "Winter Greens" category messed up the call to action blocks.

Fix call to action blocks on storefront page

---

packages/web-app/src/modules/salad-bowl/definitions/gminer.tsx
packages/web-app/src/modules/salad-bowl/definitions/phoenix-miner.tsx
packages/web-app/src/modules/salad-bowl/definitions/windows/gminer-cuckoocycle.tsx

Updates to PhoenixMiner 5.5c. Updates to GMiner 2.44. Upgrades the plugin definition configuration to support the latest Grin hardfork.

Update PhoenixMiner and GMiner and upgrade for Grin hardfork

---

packages/web-app/src/modules/error-views/components/AntiVirusFirewallErrorPage.tsx

Accidently left `Anti-Virus` on the copy for a firewall page when it should say `Firewall`

Fixed copy on the firewall page

---

packages/web-app/src/modules/salad-bowl/definitions/gminer.tsx
packages/web-app/src/modules/salad-bowl/definitions/windows/xmrig-kawpow.tsx
packages/web-app/src/modules/salad-bowl/definitions/windows/xmrig-randomx.tsx
packages/web-app/src/modules/salad-bowl/definitions/xmrig.tsx

- Update to GMiner 2.54
- Update to XMRig 6.12.1
- Fixes XMRig mining errors due to incorrect plugin download

Update GMiner and XMRig plugin definitions

---

CONTRIBUTING.md

The #feature-requests Discord channel is no longer open for discussion and only links to the forums. As such it is kind of redundant. Also added a little additional info for good measure.

Remove reference to #feature-requests

---

packages/web-app/src/modules/vault/VaultStore.ts

"Some codes have leading or trailing white space, need to remove this white space when we load the data for the reward vault"

Trimming whitespace in rewardValueItem.code

---

packages/web-app/src/modules/profile/ProfileStore.ts

I remember hearing we don't want to add the default avatar to the api call because it could end up getting expensive when we could just add it on client side. This was a way I found to do it but if you have any suggestions to make this cleaner, please feel free to let me know :)

Allow default salad avatar selection

---

packages/web-app/src/modules/seasons-views/pages/CurrentSeasonPage.tsx

[React-Multi-Carousel unfortunately does not allow you to start at a non-zero index](https://github.com/YIZHUANG/react-multi-carousel/issues/150)  so I had to reorder the array to have the current level be the first item. I had to make the carousel infinite so if you go to the left of your current level, you can still see the earlier levels.

Carousel Scroll for Levels

---

packages/web-app/src/modules/machine-views/MinerTypeContainer.ts
packages/web-app/src/modules/machine-views/components/MinerTypePanel.tsx

i saw we have a `showModal` function but it looks it's just changing the routing. the smartlink is doing the same thing so i used that because i didn't want to expose the `showModal` function to the `MinerTypePanelContainer`.

Add antivirus help link

---

packages/web-app/src/PrivateRoute.tsx
packages/web-app/src/Store.ts
packages/web-app/src/modules/auth/AuthStore.ts
packages/web-app/src/modules/salad-bowl/SaladBowlStore.ts

our `isAuthenticated` flag was previously set to an initial state of false even if this wasn't the actual state and this caused our `autoRun` function to be run twice (which would make `onLogout` run). Once on initial run, and once again after the `isAuthenticated` flag has been accurately set. This PR sets `isAuthenticated` to an initial state of undefined and exits the `autoRun` function if undefined which ensures we run `onLogin` or `onLogout` accurately.

Autorun fix

---

packages/web-app/src/modules/seasons/SeasonsStore.ts

We were only counting down by hours before. Now we are counting down by both days and hours for our next season. We're comparing at the ms so if we have a date at plus 2 hour, it will always show as 1 hour because the amount of ms that have gone by since calling that function will make it round down. 
I took screenshots of when i was testing to confirm that it's working as expected 
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>

Season Countdown Update

---

packages/web-app/src/Store.ts
packages/web-app/src/modules/onboarding-views/AutoStartConfigurationContainer.tsx
packages/web-app/src/modules/onboarding-views/pages/AutoStartConfigurationPage.tsx
packages/web-app/src/modules/onboarding/OnboardingAutoStartStore.tsx
packages/web-app/src/modules/onboarding/OnboardingStore.tsx
packages/web-app/src/modules/onboarding/index.tsx

If users have not enabled auto-start during their onboarding process, we will show the auto-start page again on startup but with a 'Do Not Show Again' checkbox. 
We only want to show this page again with the do not show again checkbox if users 
- have not seen the auto-start page before
- are on the desktop app
- don't have auto-start enabled
- haven't checked 'do not show me again'

Show Autostart Page if Autostart Not Enabled

---

packages/web-app/.env.development

In preparation for production support of the feature flags service, the test server was migrated to a new address. This updates to use the new address.

Update feature flags server address

---

packages/web-app/src/modules/zendesk/Zendesk.ts
packages/web-app/src/modules/zendesk/models/ZendeskWebWidget.ts

Swaps out the Zendesk support widget for the Intercom support widget if enabled by a feature flag.
This is a far from complete Intercom integration, and the feature flag does not touch/affect the Zendesk guides loaded in our modals. This PR enables the bare minimum to help us test & demo the Intercom platform features.

Add experiment for the Intercom support widget

---

packages/web-app/src/config.ts

when we would search for things before, we would always hit the prod server. we now have an option to hit other backends when searching. 
before:
after:

Adds override option for searchKey and searchEngine

---

packages/web-app/src/modules/xp/ExperienceStore.ts
packages/web-app/src/modules/xp/models/defaultLevels.ts

If a user has reached the XP level required to get all the vegies(131400) in the pantry, the animation will stop moving.

Fix Pantry Animation Bug

---

packages/web-app/src/Routes.tsx
packages/web-app/src/modules/storefront-views/pages/StorefrontHomePage.tsx

- This also removes the use of the Private Route component in the routes for account pages. Those pages are already handling unauthenticated users by presenting a login modal instead of showing the actual component.

Fixes bug where incorrect route would not redirect back to home page

---

packages/web-app/src/Store.ts
packages/web-app/src/modules/onboarding/OnboardingStore.tsx

Since all onboarding pages are tracked via local storage, if a different user logs into the Salad App on a friends computer for the first time, they will never see a welcome or referral code onboarding page. Resetting these account onboarding pages on logout will allow for a different user to setup their account in this scenario.

Reset account onboarding pages completed on logout

---

packages/web-app/src/FeatureManager.tsx

This slows things down a bit. Our users won't see updates all that quickly, so there's no need to use up the extra bandwidth.

Use 60 second intervals for feature toggle updates & reporting

---

packages/web-app/src/modules/zendesk/Zendesk.ts

The Help Scout Beacon dev tools are no longer necessary. This removes them as we prepare for our migration.

Remove Help Scout Beacon dev tools

---

packages/desktop-app/src/main.ts

on both my rx580 desktop and my 1660 ti laptop I got the same error so I thought I'd pr my fix. (both running archlinux and building it manually)
this is a fix for
```js
Error sending from webFrameMain: Error: Failed to serialize arguments
at Object.n.send (node:electron/js2c/browser_init:165:417)
at Object.send (node:electron/js2c/browser_init:161:2492)
at SaladBridge.send (/opt/Salad/resources/app.asar/webpack:src/SaladBridge.ts:21:29)
at /opt/Salad/resources/app.asar/webpack:src/main.ts:381:14
```
based on that there was a part of the object returned from the hardware polling lib salad uses that prevents serialization for sending to the "web" component, in order to fix this I use json to serialize and then deserialize it,
json's seriailizer will skip un-serializable parts (usually …

Fix for linux bug on some machines preventing drivers from being recognized

---

packages/web-app/src/modules/earn-views/MiningInformationContainer.ts
packages/web-app/src/modules/earn-views/components/MiningInformation.stories.tsx
packages/web-app/src/modules/earn-views/components/MiningInformation.tsx

we had a link to the desktop settings page that would always show even in the webapp. this page wasn't accessible though unless you were in the desktop app so i added a check to see if we're in the native app. the path has also changed so i updated it.

[Bug] broken Auto Start link

---

packages/web-app/src/components/SmartLink.tsx
packages/web-app/src/modules/earn-views/components/MiningInformation.tsx

We had a couple of links that were opening in new windows but we wanted them to open in the same window. 
I'm not super in love with the way I did this but because the base url is different, I couldn't just do a `to="/article"` which would open in the same window. I changed our `SmartLink` component to have an optional prop called `openInSameWindow` which removes the `target='_blank'`. This doesn't change the behavior of any of our existing `SmartLink` component uses.
Please let me know if there's another way you would prefer for this to work.

[Bug] Open Earn FAQ links in same window

---

packages/web-app/src/Routes.tsx

This sets up redirects for legacy Top Chops links. This enables compatibility for the links in both the alpha and non-alpha versions of the app.

Redirect legacy Top Chops links

---

packages/web-app/src/modules/salad-bowl/definitions/windows/xmrig-kawpow.tsx

Prohashing is having some issues with KAWPOW. This temporarily disables that configuration while their issues get sorted.

Temporarily disable KAWPOW on Prohashing

---

packages/web-app/src/modules/salad-bowl/definitions/gminer.tsx

Updates Gminer to v2.75. This should fix some errant "Anti-hacking error detected" on some modern NVIDIA drivers.

Update Gminer to v2.75

---

packages/web-app/src/modules/salad-bowl/definitions/phoenix-miner.tsx

Updates PhoenixMiner to 6.0c. This release supports a basic implementation of an LHR unlock for most NVIDIA LHR GPU models. No additional argument changes are necessary, it should auto-detect LHR GPUs with a default unlock intensity.  
Please also merge.

Updates PhoenixMiner to 6.0c

---

packages/web-app/src/modules/onboarding-views/OnboardingSpecificAntivirusGuideContainer.tsx
packages/web-app/src/modules/onboarding-views/pages/AntivirusGuide.tsx
packages/web-app/src/modules/onboarding/OnboardingAntivirusStore.tsx
packages/web-app/src/modules/zendesk/Zendesk.ts
packages/web-app/src/modules/zendesk/utils.ts

Just a quick fix for making sure our AV guides are being displayed for now. I only touched what I needed to get this fix out the door. We're going to need to eventually come back and rip out all this zendesk stuff and come up with a more permanent solution.  
From what I could tell after checking the routes, the only articles we were displaying from zendesk were the AV ones.
http://localhost:3000/onboarding/antivirus-guide/360033124692
http://localhost:3000/onboarding/antivirus-guide/360042153731

AV helpscout articles

---

packages/web-app/src/modules/error-views/FirewallErrorContainer.ts
packages/web-app/src/modules/error-views/GenericAntiVirusErrorContainer.ts
packages/web-app/src/modules/error-views/SpecificAntiVirusErrorContainer.ts
packages/web-app/src/modules/error-views/components/AntiVirusErrorPage.stories.tsx
packages/web-app/src/modules/error-views/components/AntiVirusFirewallErrorPage.tsx
packages/web-app/src/modules/onboarding-views/OnboardingSpecificAntivirusGuideContainer.tsx
packages/web-app/src/modules/onboarding-views/pages/AntivirusGuide.tsx
packages/web-app/src/modules/onboarding/OnboardingAntivirusStore.tsx
packages/web-app/src/modules/zendesk/Zendesk.ts
packages/web-app/src/modules/zendesk/utils.ts

the onboarding pages will be the same but in our alpha branch, we are using the `error/` routes. of the error routes, only the three below were pulling from zendesk
**- `/errors/anti-virus/:id`**
clicking the link will bring us to the generic antivirus route.
**- `/errors/anti-virus/`** 
**- `/errors/firewall`**

Loading Helpscout AV articles

---

packages/web-app/src/modules/salad-bowl/definitions/windows/index.tsx

ETC mining profitability has just shot up above KawPow. This shifts the priority to running ETCHASH over KawPow.
Please also merge, thanks.

Changes miner profitability order to ETC first

---

packages/web-app/src/modules/salad-bowl/definitions/windows/index.tsx

ETC mining profitability has just shot up above KawPow. This shifts the priority to running ETCHASH over KawPow.
Please also merge, thanks.

Updates miner profitability order to ETC first

---

packages/desktop-app-obliterator/obliterator.nsi

Adds the new `C:\ProgramData\Salad` path to the obliterator. This path is used in the 1.0 builds of the Salad desktop app.

Add new ProgramData path to the obliterator

---

packages/web-app/src/modules/salad-bowl/definitions/windows/index.tsx

KawPow has now overtaken ETC as more profitable for 4GB VRAM GPUs, this PR changes the order of algorithms again. Please also merge, thanks.

Changes profitability order to KawPow above ETC

---

packages/web-app/src/modules/salad-bowl/definitions/windows/index.tsx

Reverts SaladTechnologies/salad-applications#917
Looks like the KawPow DAG file is too large for some systems due to Windows pre-allocating too much VRAM to itself, preventing the (only 3.3GB) DAG from being able to fit for some 4GB GPU users.

Revert "Changes profitability order to KawPow above ETC"

---

packages/web-app/src/modules/salad-bowl/definitions/phoenix-miner.tsx

Validates support for latest AMD drivers, as well as better support for older NVIDIA and AMD driver versions. Please also merge, thanks.

Updates PhoenixMiner to v6.2c

---

packages/web-app/src/Routes.tsx
packages/web-app/src/Store.ts
packages/web-app/src/modules/salad-card-views/SaladCardEnrollmentPageContainer.tsx
packages/web-app/src/modules/salad-card-views/pages/SaladCardEnrollmentPage.tsx
packages/web-app/src/modules/salad-card/SaladCardStore.ts

Copy and designs haven't been finalized but we wanted to get at least this place holder page in. 
- The `Get SaladCard` button isn't clickable until you agree to the terms and service. 
- After clicking the button, we make a post call to the SaladCard api Dima and Joe built which creates a card. After the card is successfully created, we push the users to the store. 
- When users first visit the `earn/saladcard` page, we run a check to see if they have a saladcard and if they do, we push them to the store.

[SaladCard] Adds SaladCard enroll page

---

node_modules/.yarn-integrity
packages/web-app/src/FeatureManager.tsx
packages/web-app/src/Store.ts
packages/web-app/src/index.tsx
packages/web-app/src/modules/analytics/AnalyticsStore.ts

There is *probably* a race condition theoretically possible that would cause events to be lost without routing to mixpanel, but I *think* that would only happen when the AnalyticsStore crashes. Hopefully this doesn't happen often? Or if it does, hopefully it bricks the program (never thought I'd say that).
I was able to verify that this code allows the program to run as normal, but I wasn't able to verify that mixpanel will get the events. None of our current feature flags have impression data enabled, and even if they did I don't actually think I have access to the mixpanel dashboard.

Unleash / Mixpanel integration

---

packages/web-app/src/modules/salad-bowl/definitions/linux/index.tsx
packages/web-app/src/modules/salad-bowl/definitions/windows/index.tsx
packages/web-app/src/modules/salad-bowl/definitions/windows/xmrig-kawpow.tsx

Removes Ethash from the legacy app in preperation for The Merge. Also re-orders a couple of algorithms, and updates the required VRAM for KawPow.

Remove Ethash

---

packages/web-app/src/modules/reward-views/components/RewardHeaderBar.tsx
packages/web-app/src/modules/reward-views/components/RewardItem.tsx
packages/web-app/src/modules/storefront-views/components/StorefrontHeroItem.tsx

on our search results (RewardItem.tsx), we are leaving off the dollar sign on the original price to save space.

[App - Master Branch] Adds dollar signs to discount rewards 

---

packages/web-app/src/modules/reward-views/components/RewardHeaderBar.tsx
packages/web-app/src/modules/reward-views/components/RewardItem.tsx
packages/web-app/src/modules/storefront-views/components/StorefrontHeroItem.tsx

on our search results (`RewardItem.tsx`), we are leaving off the dollar sign on the original price to save space.

[App -Alpha Branch] Adds dollar signs to discount rewards

---

packages/web-app/src/modules/reward/RewardStore.ts

This one shows a popup when a user tries to redeem not having enough XP.

handle redemption xp error

---

packages/web-app/src/modules/xp-views/components/Pantry.tsx

**Description:**
Make pentry icons visible
**Issue:** https://www.notion.so/saladtech/Defect-432-Pantry-icons-invisible-69518243413d40f483fe83abdf112556

[App - Master Branch] Make pentry icons visible

---

packages/web-app/src/modules/xp-views/components/Pantry.tsx

**Description:**
Make pentry icons visible
**Issue:** https://www.notion.so/saladtech/Defect-432-Pantry-icons-invisible-69518243413d40f483fe83abdf112556

[App - Alpha Branch] Make pentry icons visible 

---

packages/web-app/src/modules/reward-views/components/RewardHeaderBar.tsx
packages/web-app/src/modules/reward-views/components/RewardItem.tsx
packages/web-app/src/modules/storefront-views/components/StorefrontHeroItem.tsx
packages/web-app/src/modules/storefront-views/components/StorefrontRewardItem.tsx

[1. Defect](https://www.notion.so/saladtech/Have-low-inventory-label-display-instead-of-discount-label-3f514b8188c64b8fb0185d7a93e8c5de)
[2. Defect](https://www.notion.so/saladtech/Discount-Price-Tag-shows-in-2-lines-when-smaller-screen-resolution-24af47db4c2d4b52a5f4c65c7e9615d1)
- add low quantity label priority over discount label
- fix spacing
- fix one-line discount % label

[App-master] Add low quantity label priority over discount label, fix one-line discount % label

---

packages/web-app/src/modules/reward-views/components/RewardHeaderBar.tsx
packages/web-app/src/modules/reward-views/components/RewardItem.tsx
packages/web-app/src/modules/storefront-views/components/StorefrontHeroItem.tsx
packages/web-app/src/modules/storefront-views/components/StorefrontRewardItem.tsx

[1. Defect](https://www.notion.so/saladtech/Have-low-inventory-label-display-instead-of-discount-label-3f514b8188c64b8fb0185d7a93e8c5de)
[2. Defect](https://www.notion.so/saladtech/Discount-Price-Tag-shows-in-2-lines-when-smaller-screen-resolution-24af47db4c2d4b52a5f4c65c7e9615d1)
- add low quantity label priority over discount label
- fix spacing
- fix one-line discount % label

[App-alpha] Add low quantity label priority over discount label, fix one-line discount label

---

packages/web-app/src/modules/storefront-views/components/StorefrontRewardItem.tsx

- Fix storefront reward discount to one line
defect - https://www.notion.so/Discount-Price-Tag-shows-in-2-lines-when-smaller-screen-resolution-24af47db4c2d4b52a5f4c65c7e9615d1

[App - master] Fix storefront reward discount to one line

---

packages/web-app/src/modules/settings-views/SettingsContainer.ts

https://www.notion.so/saladtech/Hide-Seasons-section-in-the-user-profile-89816fe52f7a484cab666cb625e461c8
Seasons section - removed from `account/summary` sidebar

[Web-App] Seasons section - removed from account/summary sidebar

---

packages/web-app/.env

This migrates the web application to the shiny, new API servers running on `salad.com`.

Migrate to `salad.com` 🥗`

---

packages/web-app/.env

This fixes the PayPal account link callback URL to use the API URL on `salad.com`.

Fix PayPal account link callback URL for salad.com

---

packages/web-app/.azure-pipelines/deploy.ps1
packages/web-app/.npmrc
packages/web-app/.vscode/settings.json

This removes the npm auth token placeholder fields in the `.npmrc` file that were required to work with 3rd party npm-compatible package repositories when running on Netlify CI.

Drop npm auth token fields that were required by Netlify CI

---

packages/web-app/.env
packages/web-app/.env.development
packages/web-app/.netlify/build.sh

This fixes an incorrect "double escaping" of the URL-encoded PayPal account link callback URL.

Fix PayPal account link callback URL

---

packages/web-app/src/modules/home-views/NavigationBarContainer.tsx
packages/web-app/src/modules/profile/ProfileStore.tsx
packages/web-app/src/modules/profile/models/Profile.tsx

https://www.notion.so/saladtech/Connect-BE-fetch-widget_first_login-data-286e07ed2d5c4787b3b9d5eb5ce7d0eb?pvs=4

[WebApp] saladBowlFirstLoginAt: in use instead of mocked data

---

packages/web-app/src/modules/home-views/NavigationBarContainer.tsx
packages/web-app/src/modules/profile/models/Profile.tsx

This date has to be changed to the actual one, before we have the feature released in production
`const installReminderFeatureReleaseDate = new Date('2023-12-13T14:45:00.711Z')`
https://www.notion.so/saladtech/Show-Install-Reminder-Banner-only-for-new-users-c4806dfbb06c4d40854ffee1fedd09c2?pvs=4

[WebApp] Show Install Reminder Banner only for new users

---

packages/web-app/src/modules/earn-views-mobile/MobileEarningSummaryContainer.tsx
packages/web-app/src/modules/earn-views-mobile/components/MobileEarningSummary.tsx

**Description:** Add totals to mobile earn summary page
**Issue:** https://www.notion.so/saladtech/Add-counts-for-earnings-in-the-last-24-hours-7-days-and-30-days-to-the-Mobile-Earn-Summary-page-c37649345a9f4d238b699640075aef4d

[WebApp] Add totals to mobile earn summary page

---

packages/web-app/src/modules/home-views/components/NavigationBarWithNovuNotifications.tsx

Fix notifications repeated mark as read requests, when we open drawer with unseen notifications

[Web-app] Fix notifications repeated mark as read requests

---

packages/web-app/src/modules/passkey-setup/utils.ts

getPasskeyCredential: credentials mediation set to conditional
to resolve Bitwarden passkey login issue

[WebApp] getPasskeyCredential: credentials mediation set to conditional

---

packages/web-app/src/components/Table/Table.tsx
packages/web-app/src/components/Table/index.ts
packages/web-app/src/components/Table/types.ts
packages/web-app/src/modules/earn-views/components/AllMachines/AllMachines.tsx
packages/web-app/src/modules/earn-views/components/AllMachines/index.ts
packages/web-app/src/modules/earn-views/components/AllMachines/mocks.ts
packages/web-app/src/modules/earn-views/pages/EarningSummaryPage.tsx

[SALAD-23959] WebApp: Reusable Table component - added
