- packages/web-app/src/modules/reward-views/SelectedRewardContainer.ts
- packages/web-app/src/modules/reward-views/components/SelectedReward.tsx
Added an onClick to show the modal of the selected reward
> SAL-669: Make selected reward clickable

- packages/desktop-app/src/config.ts
- packages/web-app/src/App.tsx
- packages/web-app/src/Routes.tsx
Moved the routes into their own component for a cleaner App.tsx
> Routes component

- packages/desktop-app/src/Ethminer.ts
- packages/desktop-app/src/config.ts
- packages/web-app/src/config.ts
- packages/web-app/src/modules/machine/NativeStore.ts
Added in the check for the error and changed the if/else into a switch where the cuda errors will fall through to the shared modal
> SAL-647: Update cuda driver error with ethminers new code

- packages/web-app/src/modules/machine/NativeStore.ts
- packages/web-app/src/modules/settings-views/windows-settings-views/components/WindowsSettings.tsx
- Fixed the issue where auto-launch was not initially being set
- Removed comment from WindowsSettings
> auto-launch was not initially being set

- packages/web-app/src/modules/xp/ExperienceStore.ts
Made veggie values inclusive so that veggies will show 100% completed for 1 tick of XP
> Made Veggie values inclusive

- packages/web-app/src/modules/xp/models/defaultLevels.ts
Added 3 new veggies and normalized lowbies
> Added 3 new veggies and normalized lowbies

- packages/web-app/src/Store.ts
- packages/web-app/src/config.ts
- packages/web-app/src/modules/data-refresh/RefreshService.ts
- packages/web-app/src/modules/reward/RewardStore.ts
- packages/web-app/src/modules/xp/ExperienceStore.ts
Xp hooked up to API, refreshService refactored
> DEV-124 Xp hooked up to API

- packages/web-app/src/modules/machine-views/StartButtonContainer.ts
- packages/web-app/src/modules/machine-views/components/StartButton.tsx
Button now pulses from dark green to medium green upon starting.
> DEV-271 Button Styling

- packages/web-app/.env
- packages/web-app/public/index.html
- packages/web-app/src/UIStore.ts
- packages/web-app/src/modules/home-views/BottomBarContainer.tsx
- packages/web-app/src/modules/profile-views/SettingsModalContainer.ts
Support url and canny added in place of zendesk
> Canny and Support DEV-368

- packages/web-app/src/modules/machine-views/components/StartButton.tsx
> Start Button Glow

- packages/web-app/src/modules/reward-views/RewardListContainer.ts
- packages/web-app/src/modules/reward-views/components/RewardList.tsx
- packages/web-app/src/modules/reward/RewardStore.ts
Loading rewards is now displayed when getting rewards.
> Is Loading UI added DEV-444

- packages/web-app/src/modules/reward-views/RewardDetailsModalContainer.tsx
- packages/web-app/src/modules/reward-views/components/RewardDetailsModal.tsx
- packages/web-app/src/modules/reward/RewardStore.ts
Button now is loading while selecting reward as current reward
> Loading button DEV-445

- packages/web-app/src/modules/referral-views/ReferralSettings.tsx
- packages/web-app/src/modules/settings-views/SettingsContainer.ts
- packages/web-app/src/modules/settings-views/components/Settings.styles.tsx
- packages/web-app/src/modules/settings-views/components/Settings.tsx
Referrals page header fixed to be more uniform, as well as some UI tweaks to Username page. Added user guidance for username change on edit and Log out button. Added Send Logs button right next to Submit bug button.
> Settings page tweaks DEV-462

- packages/web-app/src/modules/profile-views/components/ProfileMenuTooltip.tsx
- packages/web-app/src/modules/profile-views/components/ProfileSummaryTitle.tsx
> Updated Alpha Badge DEV-418

- packages/web-app/src/modules/settings-views/account-views/components/EditUsername.tsx
Copy change, added cancel button, and added requirements only when editing.
> Username Tweaks

- packages/web-app/src/modules/settings-views/SettingsContainer.ts
> Pointed back to Canny DEV-529

- packages/desktop-app/src/Ethminer.ts
- packages/web-app/src/Routes.tsx
- packages/web-app/src/modules/error-views/NetworkErrorContainer.ts
- packages/web-app/src/modules/error-views/components/NetworkErrorPage.tsx
- packages/web-app/src/modules/error-views/index.ts
- packages/web-app/src/modules/machine/NativeStore.ts
- Added individual codes for network errors
- Cleaned up some of the code so to use the errorCode variable
- Added shell changes to match network errors
> DEV-574 Network Error

- packages/web-app/src/modules/profile-views/components/UserStatsSummary.tsx
- When creating a new component for an info tooltip the data of the tooltip was always overwritten by the data in the ALPHA RELEASE tooltip
- Added tooltip code to the UserStatusSummary in an effort to move on from this story
> WIP: DEV-495 Mining Status tooltip

- packages/web-app/src/modules/error-views/components/AntiVirusErrorPage.tsx
Changed error text to be more accurate.
> Changed AV Error Text DEV-604

- packages/web-app/src/modules/home-views/NotificationBannerContainer.tsx
1.5x earning rate from 12/2 at 4pm MST -> 12/4 at 4pm MST
> Banner Change

- packages/web-app/src/modules/salad-bowl/PluginDefinitionFactory.ts
I tested this on multiple machines for a few days so I'm confident it won't blow up the app.
> Updated to a self-hosted version of the most recent GMiner code.

- packages/desktop-app/src/salad-bowl/Plugin.ts
- packages/web-app/src/modules/salad-bowl/PluginDefinitionFactory.ts
Claymore is currently pointing to version 15 and is inactive.
> Adding the Claymore miner definition.

- packages/web-app/src/SaladTheme.ts
- packages/web-app/src/UIStore.ts
- packages/web-app/src/modules/home-views/MainTitlebarContainer.tsx
- packages/web-app/src/modules/home-views/components/Titlebar.tsx
- packages/web-app/src/modules/profile/ProfileStore.ts
- Added a red dot to the Referrals link that indicates the user should click on it
- The dot goes away after the first time they click on it after onboarding
> Referral notification

- packages/web-app/src/modules/salad-bowl/PluginDefinitionFactory.ts
- packages/web-app/src/modules/salad-bowl/definitions/getCCMinerEquihashDefinition.ts
- packages/web-app/src/modules/salad-bowl/definitions/getCCMinerLyra2rev3Definition.ts
- packages/web-app/src/modules/salad-bowl/definitions/getCCMinerX16rDefinition.ts
- packages/web-app/src/modules/salad-bowl/definitions/getXMRigCUDADefinition.ts
- packages/web-app/src/modules/salad-bowl/definitions/getXMRigOpenCLDefinition.ts
Added and enabled the following mining definitions:
- CCMiner X16r
- CCMiner Lyra2rev3
- CCMiner Equihash
- XMRig CUDA
- XMRig OpenCL
> Adding additional miners.

- packages/web-app/src/Routes.tsx
- packages/web-app/src/UIStore.ts
- packages/web-app/src/modules/home-views/MainTitlebarContainer.tsx
- packages/web-app/src/modules/home-views/components/Titlebar.tsx
- packages/web-app/src/modules/onboarding-views/components/WhatsNewPage.tsx
- packages/web-app/src/modules/profile/ProfileStore.ts
- Removed referral page from onboarding
- Added top nav link for What's New when the Config.whatsNewVersion is different
> Adding in the What's New link to the dashboard

- packages/web-app/src/modules/salad-bowl/PluginDefinitionFactory.ts
- packages/web-app/src/modules/salad-bowl/definitions/getClaymoreEthashBitflyDefinition.ts
- packages/web-app/src/modules/salad-bowl/definitions/getClaymoreEthashDefinition.ts
- packages/web-app/src/modules/salad-bowl/definitions/getGminerBeamBitflyDefinition.ts
- packages/web-app/src/modules/salad-bowl/definitions/getGminerCuckARoom29Definition.ts
- packages/web-app/src/modules/salad-bowl/definitions/getGminerZHashDefinition.ts
This introduces a plugin definition that points to Flypool (a Bitfly pool). This exists as a fallback option in the event NiceHash has complete pool outages.
> Add GMiner+Beam+Flypool plugin definition DEV-991

- packages/web-app/src/modules/salad-bowl/PluginDefinitionFactory.ts
A little probability never hurt anyone.
> Add a 25% chance to trying Beam on NiceHash DEV-1022

- packages/web-app/src/modules/reward-views/pages/MainStorefrontPage.tsx
- packages/web-app/src/modules/reward/models/Reward.ts
- packages/web-app/src/modules/reward/utils.ts
Closes SaladTechnologies/salad-platform#305
> Connected new Reward models/APIs

- packages/web-app/src/components/SearchBar.stories.tsx
- packages/web-app/src/components/SearchBar.tsx
- packages/web-app/src/components/index.ts
- packages/web-app/src/modules/home-views/HomePage.tsx
- packages/web-app/src/modules/home-views/components/Titlebar.tsx
- packages/web-app/src/modules/reward-views/RewardSearchBarContainer.tsx
- packages/web-app/src/modules/reward-views/RewardSearchResultContainer.tsx
- packages/web-app/src/modules/reward-views/components/RewardImageCarousel.tsx
- packages/web-app/src/modules/reward-views/components/RewardSlider.tsx
- packages/web-app/src/modules/reward-views/index.ts
- packages/web-app/src/modules/reward-views/pages/BrowseRewardsPage.tsx
- packages/web-app/src/modules/reward-views/pages/RewardPages.stories.tsx
- packages/web-app/src/modules/reward-views/pages/index.ts
- packages/web-app/src/modules/reward/RewardStore.ts
- packages/web-app/src/modules/reward/models/RewardResource.ts
- packages/web-app/src/modules/reward/utils.ts
https://github.com/SaladTechnologies/salad-platform/issues/313
> Added rewards search bar

- packages/web-app/.storybook/decorators/SaladTheme.tsx
- packages/web-app/package.json
- packages/web-app/src/index.tsx
- packages/web-app/src/modules/reward-views/components/RewardHeroItem.tsx
- packages/web-app/src/modules/reward-views/components/RewardItem.tsx
- packages/web-app/src/modules/reward-views/pages/MainStorefrontPage.tsx
- packages/web-app/src/modules/reward-views/pages/RewardPages.stories.tsx
- packages/web-app/src/modules/reward/RewardStore.ts
- packages/web-app/yarn.lock
https://github.com/SaladTechnologies/salad-platform/issues/315
> Added loading skeletons, updated default category order

- packages/web-app/src/UIStore.ts
- packages/web-app/src/modules/analytics/AnalyticsStore.ts
- packages/web-app/src/modules/chopping-cart-views/ChoppingCartButtonContainer.tsx
- packages/web-app/src/modules/home-views/HomePage.tsx
- packages/web-app/src/modules/reward-views/MainStorefrontContainer.tsx
- packages/web-app/src/modules/reward-views/RewardBrowseCategoryContainer.tsx
- packages/web-app/src/modules/reward-views/RewardSearchResultContainer.tsx
- packages/web-app/src/modules/reward-views/components/RewardComponents.stories.tsx
- packages/web-app/src/modules/reward-views/components/RewardSlider.tsx
- packages/web-app/src/modules/reward-views/index.ts
- packages/web-app/src/modules/reward-views/pages/BrowseRewardsPage.tsx
- packages/web-app/src/modules/reward-views/pages/MainStorefrontPage.tsx
- packages/web-app/src/modules/reward-views/pages/RewardPages.stories.tsx
- packages/web-app/src/modules/reward/RewardStore.ts
- packages/web-app/src/modules/reward/models/Reward.ts
- packages/web-app/src/modules/reward/models/RewardCategory.ts
- packages/web-app/src/modules/reward/models/RewardResource.ts
- packages/web-app/src/modules/reward/utils.ts
https://github.com/SaladTechnologies/salad-platform/issues/314
> Added "Explore All" button to each reward category 

- packages/web-app/src/modules/reward/RewardStore.ts
- packages/web-app/tsconfig.json
https://github.com/SaladTechnologies/salad-platform/issues/317
> Sort rewards by stock & name

- packages/web-app/src/components/Scrollbar.tsx
- packages/web-app/src/modules/onboarding-views/components/WhatsNewPage.tsx
https://github.com/SaladTechnologies/salad-platform/issues/323
> Added Storefront & SaladPay what's new

- packages/web-app/src/Routes.tsx
- packages/web-app/src/UIStore.ts
- packages/web-app/src/modules/home-views/MainTitlebarContainer.tsx
- packages/web-app/src/modules/home-views/components/Titlebar.tsx
- packages/web-app/src/modules/machine/AutoStartStore.ts
- packages/web-app/src/modules/notifications/NotificationStore.tsx
- packages/web-app/src/modules/notifications/components/NotificationToast.tsx
- packages/web-app/src/modules/notifications/models/NotificationMessage.ts
- packages/web-app/src/modules/onboarding-views/WhatsNewPageContainer.ts
- packages/web-app/src/modules/onboarding-views/components/WhatsNewPage.tsx
- packages/web-app/src/modules/profile/ProfileStore.ts
- packages/web-app/src/modules/reward/RewardStore.ts
https://github.com/SaladTechnologies/salad-platform/issues/385
> Moved What's new to a toast notification

- packages/web-app/src/modules/analytics/AnalyticsStore.ts
https://github.com/SaladTechnologies/salad-platform/issues/389
> Added an AutoStart people property

- packages/web-app/src/modules/salad-bowl/SaladBowlStore.ts
https://github.com/SaladTechnologies/salad-platform/issues/324
> Added onClick to autostart notification

- packages/web-app/src/modules/settings-views/referral-views/components/CurrentReferralPanel.tsx
*disclaimer: First time contributing here. I have absolutely no idea if I should be the one doing this or if it actually works, because the instructions in the README file don't seem to be working (and the CONTRIBUTING file is nonexistent) - so sorry in advance if I messed up something here
> Typo fix for referral panel

- packages/web-app/src/modules/reward/RewardStore.ts
https://github.com/SaladTechnologies/salad-platform/issues/391
> Clicking on a reward redemption notification opens the reward vault

- packages/web-app/src/modules/home-views/components/Titlebar.tsx
https://github.com/SaladTechnologies/salad-platform/issues/395
> Added help `?`button to title bar

- packages/web-app/src/modules/analytics/AnalyticsStore.ts
- packages/web-app/src/modules/auth/AuthStore.ts
https://github.com/SaladTechnologies/salad-platform/issues/346
> Added mixpanel Id merge to connect SaladId with Auth0 Id

- packages/web-app/src/Store.ts
- packages/web-app/src/modules/engagement/EngagementStore.ts
- packages/web-app/src/modules/engagement/index.ts
- packages/web-app/src/modules/profile/ProfileStore.ts
https://github.com/SaladTechnologies/salad-platform/issues/402
> Added EngagementStore to show notifications to help new users

- packages/web-app/src/modules/engagement/EngagementStore.ts
- packages/web-app/src/modules/reward-views/components/RewardItem.tsx
https://github.com/SaladTechnologies/salad-platform/issues/451
> Ensure only 1 engagement notification is ever shown

- packages/web-app/public/index.html
- packages/web-app/src/UIStore.ts
- packages/web-app/src/modules/profile-views/SettingsModalContainer.ts
- packages/web-app/src/modules/settings-views/SettingsContainer.ts
https://github.com/SaladTechnologies/salad-platform/issues/452
> Removed link to Canny

- packages/web-app/.storybook/preview.js
- packages/web-app/src/modules/machine-views/components/CompatibilityCheckPage.tsx
- packages/web-app/src/modules/machine-views/components/StartButton.tsx
https://github.com/SaladTechnologies/salad-platform/issues/386
> Added offerwall info and links to incompatible machine pages

- packages/desktop-app/src/SaladBridge.ts
- packages/web-app/src/modules/machine/NativeStore.ts
https://github.com/SaladTechnologies/salad-platform/issues/408
> Ignore idle time messages in logs

- packages/web-app/src/modules/reward/RewardStore.ts
https://github.com/SaladTechnologies/salad-platform/issues/481
> Remove duplicate rewards

- packages/web-app/src/modules/earn-views/EarnMenuContainer.tsx
- packages/web-app/src/modules/home-views/MainTitlebarContainer.tsx
https://github.com/SaladTechnologies/salad-platform/issues/480
> Changed default earn page and added referrals to "Earn"

- packages/web-app/src/modules/salad-bowl/PluginDefinitionFactory.ts
- packages/web-app/src/modules/salad-bowl/definitions/getPhoenixMinerEthashBitflyDefinition.ts
- packages/web-app/src/modules/salad-bowl/definitions/getPhoenixMinerEthashDefinition.ts
- packages/web-app/src/modules/salad-bowl/definitions/getPhoenixMinerEthashNanopoolDefinition.ts
PhoenixMiner is also preferred over Claymore when mining Ethereum on compatible cards.
> Added PhoenixMiner as a new Ethereum mining option

- packages/web-app/src/modules/salad-bowl/PluginDefinitionFactory.ts
- packages/web-app/src/modules/salad-bowl/SaladBowlStore.ts
- packages/web-app/src/modules/salad-bowl/definitions/getCCMinerLyra2REv3Definition.ts
- packages/web-app/src/modules/salad-bowl/definitions/getCCMinerX16RDefinition.ts
- packages/web-app/src/modules/salad-bowl/definitions/getClaymoreEthashBitflyDefinition.ts
- packages/web-app/src/modules/salad-bowl/definitions/getClaymoreEthashDefinition.ts
- packages/web-app/src/modules/salad-bowl/definitions/getClaymoreEthashNanopoolDefinition.ts
- packages/web-app/src/modules/salad-bowl/definitions/getGminerBeamBitflyDefinition.ts
- packages/web-app/src/modules/salad-bowl/definitions/getGminerBeamHashIIDefinition.ts
- packages/web-app/src/modules/salad-bowl/definitions/getGminerCuckARoom29Definition.ts
- packages/web-app/src/modules/salad-bowl/definitions/getGminerZHashDefinition.ts
- packages/web-app/src/modules/salad-bowl/definitions/getPhoenixMinerEthashBitflyDefinition.ts
- packages/web-app/src/modules/salad-bowl/definitions/getPhoenixMinerEthashDefinition.ts
- packages/web-app/src/modules/salad-bowl/definitions/getPhoenixMinerEthashNanopoolDefinition.ts
- packages/web-app/src/modules/salad-bowl/definitions/getXMRigRandomXCUDADefinition.ts
- packages/web-app/src/modules/salad-bowl/definitions/getXMRigRandomXOpenCLDefinition.ts
Higher end cards will now be restricted to mining Ether, BEAM, and Grin. Lower end cards will no longer attempt to mine Grin, which would never have worked for them.
> Improved filtering on plugin definition selection.

- packages/web-app/src/modules/salad-bowl/SaladBowlStore.ts
https://github.com/SaladTechnologies/salad-platform/issues/515
> Calculate time since the start button was pressed

- packages/web-app/src/modules/salad-bowl/definitions/getClaymoreEthashBitflyDefinition.ts
- packages/web-app/src/modules/salad-bowl/definitions/getClaymoreEthashDefinition.ts
- packages/web-app/src/modules/salad-bowl/definitions/getClaymoreEthashNanopoolDefinition.ts
- packages/web-app/src/modules/salad-bowl/definitions/getPhoenixMinerEthashBitflyDefinition.ts
- packages/web-app/src/modules/salad-bowl/definitions/getPhoenixMinerEthashDefinition.ts
- packages/web-app/src/modules/salad-bowl/definitions/getPhoenixMinerEthashNanopoolDefinition.ts
This lets users optimistically try to run the mining clients even if they fail the check for the initial VRAM resolution.
> Added parameters to attempt to mitigate 4GB VRAM requirements.

- packages/web-app/src/components/SearchBar.tsx
- packages/web-app/src/modules/home-views/HomePage.tsx
- packages/web-app/src/modules/home-views/components/Titlebar.tsx
- packages/web-app/src/modules/reward-views/pages/MainStorefrontPage.tsx
https://github.com/SaladTechnologies/salad-platform/issues/409
> Moved search bar

- packages/web-app/src/modules/machine/models/MiningStatus.ts
https://github.com/SaladTechnologies/salad-platform/issues/511
> 'Renamed' running to 'Chopping'

- packages/web-app/src/App.tsx
- packages/web-app/src/Store.ts
- packages/web-app/src/modules/profile/ProfileStore.ts
https://github.com/SaladTechnologies/salad-platform/issues/457
> Allow any page to be refreshed without redirecting back to home

- packages/web-app/src/modules/earn-views/components/MiningInformation.tsx
- packages/web-app/src/modules/earn-views/components/MiningSummary.tsx
https://github.com/SaladTechnologies/salad-platform/issues/523
> Added copy explaining XP

- packages/desktop-app/src/config.ts
- packages/web-app/src/App.tsx
- packages/web-app/src/components/SettingsPage.tsx
- packages/web-app/src/components/elements/lists/LinkListUnstyled.tsx
- packages/web-app/src/modules/account-views/referral-views/components/ReferralList.tsx
- packages/web-app/src/modules/earn-views/components/EarningHistory.tsx
- packages/web-app/src/modules/home-views/FooterBarContainer.tsx
- packages/web-app/src/modules/home-views/components/FooterBar.stories.tsx
- packages/web-app/src/modules/home-views/components/FooterBar.tsx
- packages/web-app/src/modules/home-views/index.ts
- packages/web-app/src/modules/referral/ReferralStore.ts
- packages/web-app/src/modules/reward-views/components/RewardDescriptionPanel.tsx
- packages/web-app/src/modules/reward-views/components/RewardImageCarousel.tsx
- packages/web-app/src/modules/reward-views/heroes/EarningHero.tsx
- packages/web-app/src/modules/reward-views/heroes/MiningHero.tsx
- packages/web-app/src/modules/reward-views/heroes/OfferwallHero.tsx
- packages/web-app/src/modules/reward-views/pages/BrowseRewardsPage.tsx
- packages/web-app/src/modules/reward-views/pages/MainStorefrontPage.tsx
https://github.com/SaladTechnologies/salad-platform/issues/545
> Added footer bar

- packages/web-app/src/App.tsx
https://github.com/SaladTechnologies/salad-platform/issues/545
> Hide footer on boarding pages

- packages/web-app/src/RouteUtils.ts
- packages/web-app/src/components/SmartLink.stories.tsx
- packages/web-app/src/components/SmartLink.tsx
- packages/web-app/src/modules/chopping-cart-views/ChoppingCartButtonContainer.tsx
- packages/web-app/src/modules/chopping-cart-views/components/ChoppingCartButton.tsx
- packages/web-app/src/modules/chopping-cart-views/components/ChoppingCartComponents.stories.tsx
- packages/web-app/src/modules/chopping-cart-views/components/ChoppingCartTooltip.tsx
- packages/web-app/src/modules/machine/NativeStore.ts
- packages/web-app/src/modules/reward-views/MainStorefrontContainer.tsx
- packages/web-app/src/modules/reward-views/RewardBrowseCategoryContainer.tsx
- packages/web-app/src/modules/reward-views/RewardSearchResultContainer.tsx
- packages/web-app/src/modules/reward-views/components/RewardComponents.stories.tsx
- packages/web-app/src/modules/reward-views/components/RewardHeroItem.tsx
- packages/web-app/src/modules/reward-views/components/RewardItem.tsx
- packages/web-app/src/modules/reward-views/components/RewardSlider.tsx
- packages/web-app/src/modules/reward-views/pages/MainStorefrontPage.tsx
- packages/web-app/src/modules/reward-views/pages/RewardPages.stories.tsx
- packages/web-app/src/modules/reward/RewardStore.ts
https://github.com/SaladTechnologies/salad-platform/issues/547
> Replaced click events with links

- packages/web-app/package.json
- packages/web-app/src/App.tsx
- packages/web-app/src/DesktopRoute.tsx
- packages/web-app/src/PrivateRoute.tsx
- packages/web-app/src/Routes.tsx
- packages/web-app/src/components/SettingsPage.styles.tsx
- packages/web-app/src/components/SettingsPage.tsx
- packages/web-app/src/modules/settings-views/SettingsContainer.ts
https://github.com/SaladTechnologies/salad-platform/issues/484
> Hide FooterBar and windows settings pages in web mode

- CONTRIBUTING.md
Removed references to canny to direct people back to Discord for feature requests
> Removed Canny

- packages/web-app/src/modules/reward-views/components/RewardHeaderBar.tsx
- packages/web-app/src/modules/reward-views/components/RewardHeroItem.tsx
- packages/web-app/src/modules/reward-views/components/RewardItem.tsx
https://github.com/SaladTechnologies/salad-platform/issues/500
> Fixed out of stock labels

- packages/web-app/src/components/SettingsPage.stories.tsx
- packages/web-app/src/components/SettingsPage.styles.tsx
- packages/web-app/src/components/SettingsPage.tsx
https://github.com/SaladTechnologies/salad-platform/issues/520
> Updated back button on settings pages

- packages/web-app/src/modules/reward-views/components/RewardImageCarousel.tsx
- packages/web-app/src/modules/reward-views/components/RewardInfoPanel.tsx
https://github.com/SaladTechnologies/salad-platform/issues/493
> Updated reward details image layouts

- packages/web-app/src/modules/home-views/FooterBarContainer.tsx
- packages/web-app/src/modules/home-views/components/FooterBar.tsx
https://github.com/SaladTechnologies/salad-platform/issues/566
> Added start button to footer bar

- packages/web-app/src/modules/machine/models/MiningStatus.ts
- packages/web-app/src/modules/salad-bowl/SaladBowlStore.ts
https://github.com/SaladTechnologies/salad-platform/issues/570
> Renamed Initializing to Prepping

- packages/web-app/src/components/index.ts
- packages/web-app/src/components/primitives/content/Li.tsx
- packages/web-app/src/modules/earn-views/components/MiningInformation.tsx
- packages/web-app/src/modules/earn-views/pages/EarningInformationPage.tsx
https://github.com/SaladTechnologies/salad-platform/issues/559
> Updated earning information copy

- packages/web-app/src/components/HeroPanel.tsx
- packages/web-app/src/components/SearchBar.tsx
- packages/web-app/src/modules/reward-views/components/RewardHeaderBar.tsx
- packages/web-app/src/modules/reward-views/components/RewardHeroButtonGroup.tsx
- packages/web-app/src/modules/reward-views/components/RewardHeroItem.tsx
- packages/web-app/src/modules/reward-views/components/RewardSlider.tsx
- packages/web-app/src/modules/reward-views/pages/BrowseRewardsPage.tsx
https://github.com/SaladTechnologies/salad-platform/issues/539
> UI Design Tweaks

- packages/web-app/src/components/ModalPage.tsx
- packages/web-app/src/modules/salad-pay/SaladPayStore.ts
https://github.com/SaladTechnologies/salad-platform/issues/580
> Fixed UI issues when opening or closing SaladPay

- packages/web-app/src/Routes.tsx
- packages/web-app/src/components/SettingsPage.tsx
- packages/web-app/src/modules/account-views/account-menu/components/AccountMenu.tsx
- packages/web-app/src/modules/home-views/components/Titlebar.tsx
- packages/web-app/src/modules/settings-views/SettingsContainer.ts
https://github.com/SaladTechnologies/salad-platform/issues/580
> Hide send logs & fixed padding on settings gear

- packages/web-app/src/modules/auth-views/EmailVerificationPageContainer.ts
- packages/web-app/src/modules/auth-views/components/EmailVerificationPage.stories.tsx
- packages/web-app/src/modules/auth-views/components/EmailVerificationPage.tsx
- packages/web-app/src/modules/auth/AuthStore.ts
- packages/web-app/src/modules/auth/TooManyRequestsError.ts
... plus a handful of additional fixes and improvements.
> Poll Auth0 for email verification status changes

- packages/web-app/package.json
- packages/web-app/src/Store.ts
- packages/web-app/src/modules/balance/BalanceStore.ts
- packages/web-app/src/modules/balance/models/EarningWindow.ts
- packages/web-app/src/modules/data-refresh/RefreshService.ts
- packages/web-app/src/modules/earn-views/EarningSummaryContainer.ts
- packages/web-app/src/modules/earn-views/components/EarningHistory.stories.tsx
- packages/web-app/src/modules/earn-views/components/EarningHistory.tsx
- packages/web-app/src/modules/earn-views/pages/EarningSummaryPage.stories.tsx
- packages/web-app/src/modules/reward/RewardStore.ts
- packages/web-app/yarn.lock
https://github.com/SaladTechnologies/salad-platform/issues/524
> Connected earnings history charts to API

- packages/web-app/src/modules/machine/NativeStore.ts
https://github.com/SaladTechnologies/salad-platform/issues/620
> Fixed login issue in desktop app

- packages/web-app/src/modules/balance/BalanceStore.ts
- packages/web-app/src/modules/balance/models/EarningWindow.ts
- packages/web-app/src/modules/earn-views/components/EarningHistory.tsx
https://github.com/SaladTechnologies/salad-platform/issues/619
> Added new visuals for current window to earning chart

- packages/web-app/src/modules/home-views/FooterBarContainer.tsx
- packages/web-app/src/modules/home-views/components/FooterBar.tsx
- packages/web-app/src/modules/machine-views/components/StartButton.tsx
- packages/web-app/src/modules/machine/NativeStore.ts
- packages/web-app/src/modules/salad-bowl/SaladBowlStore.ts
https://github.com/SaladTechnologies/salad-platform/issues/622
> Fixed running time label and machine registration

- packages/web-app/src/modules/analytics/AnalyticsStore.ts
- packages/web-app/src/modules/salad-bowl/SaladBowlStore.ts
https://github.com/SaladTechnologies/salad-platform/issues/624
> Added total and chopping time to stop event

- packages/web-app/src/axiosFactory.ts
https://github.com/SaladTechnologies/salad-platform/issues/631
> Added error message for redemptions:disabled

- packages/web-app/src/modules/salad-bowl/PluginDefinitionFactory.ts
- packages/web-app/src/modules/salad-bowl/definitions/getGminerBeamBitflyDefinition.ts
- packages/web-app/src/modules/salad-bowl/definitions/getGminerBeamNiceHashDefinition.ts
- packages/web-app/src/modules/salad-bowl/definitions/getGminerCuckARoom29Definition.ts
- packages/web-app/src/modules/salad-bowl/definitions/getGminerZHashDefinition.ts
This updates our BEAM plugin definitions to Gminer v2.11.
> Add support for BeamHashIII

- packages/web-app/src/modules/account-views/account-menu/components/AccountMenu.tsx
- packages/web-app/src/modules/earn-views/components/EarningHistory.tsx
- packages/web-app/src/modules/earn-views/components/EarningSummary.tsx
- packages/web-app/src/utils.ts
https://github.com/SaladTechnologies/salad-platform/issues/647
> Updated balance formatter to support tiny balance amouts

- packages/web-app/build.sh
- packages/web-app/src/modules/salad-bowl/models/StartReason.ts
- packages/web-app/src/modules/versions/VersionStore.ts
https://github.com/SaladTechnologies/salad-platform/issues/646
> Auto refresh if web version is out of date

- packages/web-app/src/modules/salad-bowl/PluginDefinitionFactory.ts
- packages/web-app/src/modules/salad-bowl/definitions/constants.ts
- packages/web-app/src/modules/salad-bowl/definitions/getCCMinerLyra2REv3Definition.ts
- packages/web-app/src/modules/salad-bowl/definitions/getCCMinerX16RDefinition.ts
- packages/web-app/src/modules/salad-bowl/definitions/getClaymoreEthashDefinition.ts
- packages/web-app/src/modules/salad-bowl/definitions/getGminerBeamNiceHashDefinition.ts
- packages/web-app/src/modules/salad-bowl/definitions/getGminerCuckARoom29Definition.ts
- packages/web-app/src/modules/salad-bowl/definitions/getGminerZHashDefinition.ts
- packages/web-app/src/modules/salad-bowl/definitions/getMiniZBeamBitflyDefinition.ts
- packages/web-app/src/modules/salad-bowl/definitions/getMiniZBeamNiceHashDefinition.ts
- packages/web-app/src/modules/salad-bowl/definitions/getMiniZZHashDefinition.ts
- packages/web-app/src/modules/salad-bowl/definitions/getPhoenixMinerEthashDefinition.ts
- packages/web-app/src/modules/salad-bowl/definitions/getXMRigRandomXCUDADefinition.ts
- packages/web-app/src/modules/salad-bowl/definitions/getXMRigRandomXOpenCLDefinition.ts
> Add support for multiple NiceHash accounts

- packages/web-app/src/modules/salad-bowl/definitions/getGminerBeamBitflyDefinition.ts
- packages/web-app/src/modules/salad-bowl/definitions/getGminerBeamNiceHashDefinition.ts
- packages/web-app/src/modules/salad-bowl/definitions/getGminerCuckARoom29Definition.ts
- packages/web-app/src/modules/salad-bowl/definitions/getGminerZHashDefinition.ts
The previous version was 2.11.
> Updated GMiner to v2.15.

- packages/web-app/src/modules/salad-bowl/definitions/getGminerBeamBitflyDefinition.ts
- packages/web-app/src/modules/salad-bowl/definitions/getGminerBeamNiceHashDefinition.ts
- packages/web-app/src/modules/salad-bowl/definitions/getGminerCuckARoom29Definition.ts
- packages/web-app/src/modules/salad-bowl/definitions/getGminerZHashDefinition.ts
The previous version was v2.11.
> Updated GMiner to v2.15 on master.

- packages/web-app/src/modules/auth/AuthStore.ts
Resolves SaladTechnologies/salad-platform#645.
> Handle redirects between login & email verification pages

- packages/web-app/src/modules/account-views/account-menu/components/AccountMenu.tsx
- packages/web-app/src/modules/auth-views/components/LoginPanel.tsx
https://github.com/SaladTechnologies/salad-platform/issues/657
> Removed the Register button

- packages/web-app/src/modules/earn-views/pages/MiningPage.tsx
- packages/web-app/src/modules/engagement/EngagementStore.ts
- packages/web-app/src/modules/machine-views/StartButtonContainer.ts
- packages/web-app/src/modules/machine-views/components/StartButton.tsx
- packages/web-app/src/modules/salad-bowl/SaladBowlStore.ts
https://github.com/SaladTechnologies/salad-platform/issues/682
> Incompatible machines

- packages/web-app/src/ErrorBoundary.tsx
- packages/web-app/src/index.tsx
This adds a nice error page with a feedback form when the app catches a fatal error. No more blank, blue screens!
> Add React ErrorBoundary and Sentry feedback form

- packages/web-app/src/components/Button.tsx
https://github.com/SaladTechnologies/salad-platform/issues/775
> Button will only stop event propagation if it is the click handler

- packages/desktop-app/src/main.ts
This adds a Salad system tray icon that can be used to hide, show, and exit the application.
> Add minimize to system tray

- .gitignore
- packages/web-app/src/modules/home-views/MainTitlebarContainer.tsx
- packages/web-app/src/modules/home-views/components/HomeViews.stories.tsx
- packages/web-app/src/modules/home-views/components/Titlebar.stories.tsx
- packages/web-app/src/modules/home-views/components/Titlebar.tsx
- packages/web-app/src/modules/machine-views/components/StartButton.tsx
- packages/web-app/src/modules/salad-bowl/SaladBowlStore.ts
https://github.com/SaladTechnologies/salad-platform/issues/779
> Added Start button to title bar

- packages/desktop-app/package.json
- packages/desktop-app/src/main.ts
- packages/desktop-app/yarn.lock
Fixes the resolution of `snoretoast-x64.exe` and restore the Windows 10 toast notifications.
> Fix Windows 10 notifications by resolving snoretoast executable path

- packages/desktop-app/package.json
- packages/desktop-app/yarn.lock
This simply updates the desktop app version to 0.4.1.
> Release desktop app 0.4.1

- packages/desktop-app/package.json
This simply updates the desktop app version to 0.4.2.
> Release desktop app 0.4.2

- packages/web-app/src/modules/salad-bowl/definitions/getTrexRavencoinNiceHashDefinition.ts
- packages/web-app/src/modules/versions/VersionStore.ts
This filters out erroneous T-Rex running checks.
> Fix T-Rex running check

- packages/desktop-app/src/main.ts
Add notification support for linux/darwin using electron's Notification. Untested on darwin, but should work out of the box.
> Notification support for linux/darwin

- packages/web-app/src/modules/analytics/AnalyticsStore.ts
- packages/web-app/src/modules/machine/NativeStore.ts
- packages/web-app/src/modules/salad-bowl/SaladBowlStore.ts
https://github.com/SaladTechnologies/salad-platform/issues/831
> Additional Analytics Parameters

- packages/desktop-app/electron-builder.json
Packages tested on Ubuntu 20.04 and OpenSUSE Leap 15.2
> Update builder config for linux. 

- packages/web-app/src/modules/reward-views/components/RewardHero.tsx
- packages/web-app/src/modules/reward-views/components/RewardSlider.tsx
https://github.com/SaladTechnologies/salad-platform/issues/687
> Fixed issue with rewards not displaying on 4K monitors

- packages/desktop-app/src/main.ts
We were not ending the function call after returning a cached copy of the machine info. This caused us to poll for the machine info again and forward it to the web app a second time.
> Prevent pulling machine info if cached info is already available

- packages/web-app/src/modules/earn-views-mobile/pages/MobileOfferwallPage.tsx
Fixes typo of **_Offer Toro_** to **_OfferToro_**
> Fix OfferToro spelling

- packages/web-app/src/MobileRoutes.tsx
- packages/web-app/src/components/MobilePageNotFound.stories.tsx
- packages/web-app/src/components/MobilePageNotFound.tsx
> Added 404 Page for routes that don't exist on the mobile app

- packages/web-app/package.json
- packages/web-app/src/components/elements/Segments/Segments.stories.tsx
- packages/web-app/src/components/elements/Segments/Segments.tsx
- packages/web-app/src/components/elements/Segments/index.ts
- packages/web-app/src/modules/balance/BalanceStore.ts
- packages/web-app/src/modules/balance/utils.ts
- packages/web-app/src/modules/earn-views-mobile/MobileEarningSummaryContainer.ts
- packages/web-app/src/modules/earn-views/EarningChartContainer.ts
- packages/web-app/src/modules/earn-views/EarningHistoryContainer.ts
- packages/web-app/src/modules/earn-views/EarningSummaryContainer.ts
- packages/web-app/src/modules/earn-views/components/EarningChart.tsx
- packages/web-app/src/modules/earn-views/components/EarningHistory.tsx
- packages/web-app/src/modules/earn-views/utils.ts
- packages/web-app/yarn.lock
Adds three new features to the EarningChart component. 
1) Adds x-axis and y-axis lines
2) Allows user to select range of earning windows to display amount earned during that range
3) Allows users to view earnings chart in time periods of last 24 hours, 7 days, or 30 Days
**Note:** This PR also includes the addition of types for lodash library.
> Adds new interactions to Earning Chart component

- packages/web-app/src/modules/earn-views/components/EarningChart.tsx
- Fixes overlapping x-axis label on Earning Chart
- Updated 30 Day x-axis label to display date instead of time
> Fixed overlap of tick labels and updated 30 Day x-axis label on Earning Chart

- packages/web-app/src/modules/versions/VersionStore.ts
Runs checkDesktopVersion API call if latestDesktopVersion observable is ever undefined.
> Ensure checkDesktopVersion is called on native app

- packages/web-app/src/modules/salad-bowl/definitions/gminer.tsx
- packages/web-app/src/modules/salad-bowl/definitions/phoenix-miner.tsx
- packages/web-app/src/modules/salad-bowl/definitions/xmrig.tsx
Adds GMiner 2.39, PhoenixMiner 5.4c, and XMRig 6.7.0.
> Update GMiner, PhoenixMiner, and XMRig

- packages/desktop-app/package.json
This simply updates the desktop app version to 0.5.0.
> Release desktop app 0.5.0

- packages/desktop-app/package.json
This simply updates the desktop app version to 0.5.1.
> Release desktop app 0.5.1

- packages/web-app/src/modules/reward-views/MainStorefrontContainer.tsx
- packages/web-app/src/modules/reward-views/RewardSearchResultContainer.tsx
- packages/web-app/src/modules/reward-views/components/RewardComponents.stories.tsx
- packages/web-app/src/modules/reward-views/components/RewardItem.tsx
- packages/web-app/src/modules/reward-views/pages/BrowseRewardsPage.tsx
- packages/web-app/src/modules/reward-views/pages/MainStorefrontPage.tsx
- packages/web-app/src/modules/reward-views/pages/RewardPages.stories.tsx
- packages/web-app/src/modules/reward-views/pages/SearchResultsPage.tsx
- packages/web-app/src/utils.ts
Adds click tracking to elasticsearch when a user clicks on a search result item. This includes a refactor of how the `RewardItem` component now takes a click event prop that handles any routing/analytic action.
> Adds elasticsearch result click tracking

- packages/web-app/src/Store.ts
- packages/web-app/src/modules/error-views/FallbackErrorContainer.ts
- packages/web-app/src/modules/error-views/components/FallbackErrorPage.tsx
- packages/web-app/src/modules/zendesk/Zendesk.ts
The updated Fallback Error Modal now provides the user with an opportunity to switch to an alternative mining type while also presenting them with helpful support links.
> Updated Fallback Error Modal

- packages/web-app/src/modules/salad-bowl/definitions/linux/phoenixminer-ethash.tsx
- packages/web-app/src/modules/salad-bowl/definitions/windows/phoenixminer-ethash.tsx
Prioritizing Ethermine over NiceHash given their recent outages and ongoing issues.
> Prioritize Ethermine plugin definitions

- packages/web-app/src/modules/error-views/FallbackErrorContainer.ts
- packages/web-app/src/modules/error-views/NotCompatibleErrorContainer.ts
- packages/web-app/src/modules/home-views/MainTitlebarContainer.tsx
- packages/web-app/src/modules/machine-views/StartButtonContainer.ts
- packages/web-app/src/modules/machine-views/TitleStartButtonContainer.ts
- packages/web-app/src/modules/machine/AutoStartStore.ts
- packages/web-app/src/modules/salad-bowl/SaladBowlStore.ts
- packages/web-app/src/modules/salad-bowl/models/StartActionType.ts
- packages/web-app/src/modules/salad-bowl/models/index.ts
Checks if user is authenticated before showing compatibility issue on Start Button click.
> Prevents unauthenticated user from seeing compatibility issue modal

- packages/web-app/src/modules/vault-views/components/NewVault.stories.tsx
- packages/web-app/src/modules/vault-views/components/NewVaultList.tsx
- packages/web-app/src/modules/vault-views/components/VaultListHeaderItem.tsx
- packages/web-app/src/modules/vault/VaultStore.ts
- packages/web-app/src/modules/vault/models/RewardVaultItem.ts
- packages/web-app/src/modules/vault/models/RewardVaultResource.ts
- packages/web-app/src/modules/vault/models/RewardVaultStatus.ts
- packages/web-app/src/modules/vault/models/index.ts
Along with new Storybook UI components, this updates the Reward Item model in the Reward Store to reflect the addition of the status property.
> Added New Reward Vault List UI to Storybook

- packages/web-app/src/modules/earn-views/components/ShowFolderSection.stories.tsx
- packages/web-app/src/modules/earn-views/components/ShowFolderSection.tsx
- packages/web-app/src/modules/earn-views/components/index.ts
Please let me know if there's anything I missed. I'm planning on hooking up the actual '`open-log-folder`' function in the next ticket. 
I've also received approval from Eric.
Thank you!
> Added ShowApplicationLogFolderSection to Storybook

- packages/web-app/src/modules/machine-views/TitleStartButtonContainer.ts
- packages/web-app/src/modules/machine-views/components/StartButton.stories.tsx
- packages/web-app/src/modules/machine-views/components/StartButton.tsx
- packages/web-app/src/modules/salad-bowl/SaladBowlStore.ts
- packages/web-app/src/modules/salad-bowl/utils.ts
1. Modifies time frames for Start Button prepping progress percentage changes
2. Updates Start Button styles to give a more animated effect while prepping
> Update start button

- packages/web-app/src/modules/salad-bowl/definitions/linux/index.tsx
- packages/web-app/src/modules/salad-bowl/definitions/linux/phoenixminer-etchash.tsx
- packages/web-app/src/modules/salad-bowl/definitions/linux/phoenixminer-ethash.tsx
- packages/web-app/src/modules/salad-bowl/definitions/windows/index.tsx
- packages/web-app/src/modules/salad-bowl/definitions/windows/phoenixminer-etchash.tsx
- packages/web-app/src/modules/salad-bowl/definitions/windows/phoenixminer-ethash.tsx
Ethereum Classic on Ethermine is a great alternative for 3GB and 4GB cards. On some hardware, this may be quite profitable.
> Add plugin definition for Ethereum Classic on Ethermine

- packages/web-app/src/modules/referral/ReferralStore.ts
Removes the referral code workarounds. The original referral codes are back in business!
> Remove referral code workarounds

- packages/web-app/src/Routes.tsx
- packages/web-app/src/Store.ts
- packages/web-app/src/modules/data-refresh/RefreshService.ts
- packages/web-app/src/modules/seasons-views/CurrentSeasonPageContainer.tsx
- packages/web-app/src/modules/seasons-views/index.tsx
- packages/web-app/src/modules/seasons-views/pages/CurrentSeasonPage.tsx
- packages/web-app/src/modules/seasons/SeasonsStore.ts
- packages/web-app/src/modules/seasons/index.ts
- packages/web-app/src/modules/seasons/models/CurrentSeason.ts
- packages/web-app/src/modules/seasons/models/index.ts
- packages/web-app/src/modules/settings-views/SettingsContainer.ts
- This PR has now been tested against the API. A follow up PR will be needed to implement the correct Levels UI to the page
> Adds Current Season Page

- packages/web-app/src/modules/account-views/account-views/components/Account.tsx
- packages/web-app/src/modules/account-views/account-views/components/AvatarSelect.tsx
the title is a little lower than it should be. i've got to make a change in the layout component in the garden and then it will all line up well. 
we also only want to show the available avatars and not a list of a bunch of blank ones.
> Profile page styling

- packages/web-app/src/App.tsx
- packages/web-app/src/modules/home-views/WindowBarContainer.tsx
- packages/web-app/src/modules/home-views/components/WindowBar.tsx
- packages/web-app/src/modules/home-views/index.tsx
- Also fixes gap between navigation bar and page content
> Adds Window Bar to Desktop App

- packages/web-app/src/modules/zendesk/Zendesk.ts
Because everyone loves to have a good chat now again. 💻
> Add support for Zendesk live chat

- packages/web-app/src/components/SearchBar.tsx
- packages/web-app/src/modules/bonus/BonusStore.ts
- packages/web-app/src/modules/home-views/NavigationBarContainer.tsx
- packages/web-app/src/modules/vault-views/components/VaultList.tsx
- Adds Bonus Card to Navigation Bar
- Sorts Bonus Cards by Date then name
- Updates use of new callback functions for desktop authenticated panel items
- Fixes Z-Index issue on Reward Vault Page
- Shows Download label when a user is on the web app
> Adds Bonus Card to Navigation Bar

- packages/web-app/src/modules/profile/ProfileStore.ts
we accidently left a 5 second wait in the avatar select promise
> Fixed Avatar Select Lag

- packages/web-app/src/modules/account-views/account-views/components/Account.tsx
- packages/web-app/src/modules/bonus-views/components/BonusPage.tsx
- packages/web-app/src/modules/seasons-views/pages/CurrentSeasonPage.tsx
Using Salad's styled scroll bar for vertical scroll on new pages. 
Also added bottom padding to the horizontal scroll on the levels in the seasons page
> Updates scrollbar styling on new pages

- packages/web-app/src/modules/account-views/referral-views/components/ReferralSettings.tsx
- packages/web-app/src/modules/bonus-views/components/BonusPage.tsx
- packages/web-app/src/modules/earn-views/components/MiningInformation.tsx
- packages/web-app/src/modules/earn-views/pages/EarningSummaryPage.tsx
- packages/web-app/src/modules/earn-views/pages/MiningPage.tsx
- [Added padding between Section Headers and Start Button](https://www.notion.so/saladtech/Engineering-Task-Board-b767926b1ec742fab701ac4d7d1e6e7b?p=ad8b48871a5e4f429446227c1f656fa4)
- [Adjusted Bonus Page card spacing ](https://www.notion.so/saladtech/Engineering-Task-Board-b767926b1ec742fab701ac4d7d1e6e7b?p=bd9c3dfca56c452aa60d16519f6af4ad)
bonus page with mock data populated:
> Misc season styling

- packages/web-app/src/modules/zendesk/Zendesk.ts
- Updates the color of the Zendesk Widget to light green to provide better contrast with our dark blue and green backgrounds in the app
> Changes Zendesk Widget to light green

- packages/web-app/src/modules/analytics/AnalyticsStore.ts
Updates the Mixpanel API endpoint and fixes a couple of minor misconfigurations.
> Update Mixpanel API endpoint

- packages/web-app/src/modules/analytics/AnalyticsStore.ts
Fixes a minor misconfiguration.
> Set Mixpanel cookie to require HTTPS

- packages/web-app/src/modules/auth-views/components/LoginPage.tsx
> Grammar fixes to login page

- packages/web-app/src/modules/analytics/AnalyticsStore.ts
- Adds checks to ensure Mixpanel events are not called when in a local environment
- Resets Sentry session on log out
> Mixpanel and Sentry session fixes

- packages/web-app/src/modules/account-views/referral-views/ReferralOnboardingContainer.ts
- packages/web-app/src/modules/account-views/referral-views/ReferralWelcomeContainer.ts
- packages/web-app/src/modules/account-views/referral-views/components/ReferralOnboardingPage.tsx
- packages/web-app/src/modules/account-views/referral-views/components/ReferralWelcomePage.tsx
- packages/web-app/src/modules/auth-views/LoginPageContainer.ts
- packages/web-app/src/modules/auth-views/components/LoginPage.tsx
- packages/web-app/src/modules/onboarding-views/AFKConfigurationContainer.tsx
- packages/web-app/src/modules/onboarding-views/pages/AFKConfigurationPage.tsx
makes sure the `<WindowBarContainer/>` isn't hidden on our onboarding pages
> Show windowbarcontainer on desktop onboarding pages

- packages/web-app/src/modules/account-views/account-views/components/Account.tsx
a couple quick font size updates that Arlo pointed out
> Updates Account Page Fonts

- packages/desktop-app/src/main.ts
- packages/desktop-app/src/preload.js
- packages/web-app/src/modules/machine/NativeStore.ts
- packages/web-app/src/modules/onboarding/OnboardingStore.tsx
This PR adds the ability to enable sleep mode on all the user's power profiles. We will still need to wire this up to the frontend.
> Add Disable Sleep Mode Function

- packages/web-app/src/modules/profile/ProfileStore.ts
need to wait on backend changes to handle `00000000-0000-0000-0000-000000000000` id to be merged in first
> Fixes Salad Logo Avatar Selection Bug

- packages/web-app/src/Routes.tsx
- packages/web-app/src/Store.ts
- packages/web-app/src/modules/balance/BalanceStore.ts
- packages/web-app/src/modules/earn-views/EarningsSummaryPageContainer.tsx
- packages/web-app/src/modules/earn-views/components/EarningChartPanel.tsx
- packages/web-app/src/modules/earn-views/index.ts
- packages/web-app/src/modules/earn-views/pages/EarningsSummaryPage.stories.tsx
- packages/web-app/src/modules/earn-views/pages/EarningsSummaryPage.tsx
- packages/web-app/src/modules/machine-views/MachineSettingsPageContainer.tsx
- packages/web-app/src/modules/machine-views/index.ts
- packages/web-app/src/modules/machine-views/pages/MachineSettingsPage.stories.tsx
- packages/web-app/src/modules/machine-views/pages/MachineSettingsPage.tsx
- packages/web-app/src/modules/machine/MachineSettingsUIStore.tsx
- packages/web-app/src/modules/machine/index.ts
- packages/web-app/src/modules/machine/models/MinerWorkload.tsx
- packages/web-app/src/modules/machine/models/ProcessorInformation.tsx
- packages/web-app/src/modules/machine/models/index.ts
- packages/web-app/src/modules/salad-bowl/SaladBowlStore.ts
- packages/web-app/src/modules/salad-bowl/SaladBowlStoreInterface.tsx
- packages/web-app/src/modules/salad-bowl/SaladForkAndBowlStore.tsx
- packages/web-app/src/services/SaladFork/SaladFork.tsx
- The two pages are guarded by the salad bowl feature flag
> Connect new Earnings Summary and Machine Settings Page 

- packages/web-app/src/modules/seasons/SeasonsStore.ts
rendering a completed on instead of a negative number now
> Season completed on 

- packages/web-app/src/modules/machine/NativeStore.ts
- packages/web-app/src/modules/onboarding-views/pages/AntivirusConfigurationPage.stories.tsx
- packages/web-app/src/modules/onboarding/OnboardingAntivirusStore.tsx
- packages/web-app/src/modules/onboarding/models/WhitelistWindowsDefenderErrorType.ts
- packages/web-app/src/modules/onboarding/models/WhitelistWindowsDefenderErrorTypeMessage.ts
- packages/web-app/src/modules/onboarding/models/index.tsx
- packages/web-app/src/utils.ts
We're now waiting 2 seconds after successfully whitelisting windows defender to show the success toast notification and push users to the store. Also updated one of the error messages
> Antivirus 2 second wait

- packages/web-app/src/modules/earn-views/components/EarningChart.tsx
- Updates font to match updated UI when salad bowl feature flag is enabled
> Updated fonts on chart for salad bowl 2.0

- packages/web-app/src/modules/seasons-views/pages/CurrentSeasonPage.tsx
> Adds FAQ link to Seasons page

- packages/web-app/src/modules/salad-bowl/definitions/linux/gminer-zhash.tsx
- packages/web-app/src/modules/salad-bowl/definitions/linux/phoenixminer-etchash.tsx
- packages/web-app/src/modules/salad-bowl/definitions/linux/phoenixminer-ethash.tsx
- packages/web-app/src/modules/salad-bowl/definitions/linux/xmrig-randomx.tsx
- packages/web-app/src/modules/salad-bowl/definitions/macos/xmrig-randomx.tsx
- packages/web-app/src/modules/salad-bowl/definitions/windows/gminer-zhash.tsx
- packages/web-app/src/modules/salad-bowl/definitions/windows/phoenixminer-etchash.tsx
- packages/web-app/src/modules/salad-bowl/definitions/windows/phoenixminer-ethash.tsx
- packages/web-app/src/modules/salad-bowl/definitions/windows/xmrig-randomx.tsx
The Prohashing workloads are enabled for all, and the feature flag has been archived. This removes it from the code base.
> Remove obsolete app_prohashing feature flag

- packages/web-app/netlify.toml
It's all in the title! This PR fixes reward search on test environment deployments. (I guess it's duplicated in the description now, too. 😜)
> Fix reward search on test environment deployments

- packages/web-app/src/modules/zendesk/Zendesk.ts
- packages/web-app/src/modules/zendesk/models/ZendeskWebWidget.ts
Re-enable the Help Scout support widget feature, behind a feature flag.
> Enable experiment for the Help Scout support widget

- packages/web-app/src/modules/zendesk/Zendesk.ts
Adds support for getting Help Scout signatures to authenticate the current user and load conversation history.
> Add Help Scout authentication

- packages/web-app/src/modules/vault-views/components/VaultList.stories.tsx
- packages/web-app/src/modules/vault/models/RewardVaultStatus.ts
> Add refunded status to reward vault

- packages/desktop-app/src/main.ts
This backports #851 to the alpha version of the app.
> Backport #851

- packages/web-app/src/components/SmartLink.tsx
- packages/web-app/src/modules/earn-views/MiningInformationContainer.ts
- packages/web-app/src/modules/earn-views/components/MiningInformation.stories.tsx
- packages/web-app/src/modules/earn-views/components/MiningInformation.tsx
Getting alpha up to date with the two link bugs i just merged into master. 
1. Fixed the Auto Start link to only be a hyperlink if we're in the native app.
2. Updated Smartlinks to only open in new window if we're in the native app.
> [Bugs] Updated links

- packages/web-app/src/modules/salad-bowl/definitions/xmrig.tsx
> Updates XMRig to 6.16.3

- packages/web-app/src/modules/salad-bowl/definitions/windows/xmrig-kawpow.tsx
Prohashing has resolved their issues with KAWPOW. This reverts #876.
> Revert "Temporarily disable KAWPOW on Prohashing"

- packages/web-app/src/modules/salad-bowl/definitions/gminer.tsx
For whoever approves review, please also merge. Thanks.
> Updates Gminer to v2.82

- packages/web-app/src/modules/salad-bowl/definitions/gminer.tsx
> updates gminer to v2.86

- packages/web-app/src/modules/salad-bowl/definitions/phoenix-miner.tsx
> Updates PhoenixMiner to v6.1b

- packages/web-app/src/modules/salad-bowl/definitions/xmrig.tsx
> Updates XMRig to v6.17.0

- packages/web-app/src/modules/auth/AuthStore.ts
if you click on any of the login buttons in the app, we will pass the path to the `redirect_uri` which will redirect you back to the page after authenticating.
> [App] Adding redirect_uri on login page

- packages/web-app/src/Routes.tsx
added required configs on unleash's platform. this adds in the code required on our side.
> [SaladCard] SaladCard feature flag

- packages/web-app/src/modules/auth/AuthStore.ts
This reverts commit 67ac25a to restore the internal login page for web-based workflows. This will help address an issue some users are encountering in browsers that block 3rd party cookies.
> Restore internal login for web-based workflows

- packages/web-app/src/modules/salad-bowl/definitions/xmrig.tsx
> Updates XMRig to v6.18.0

- packages/web-app/src/Routes.tsx
- packages/web-app/src/Store.ts
- packages/web-app/src/modules/earn-views/components/EarningChart.tsx
Removes references to `app_saladcard` and `app_salad_bowl` feature flags in the master branch
> [App] Remove outdated feature flags (master branch)

- packages/web-app/src/Routes.tsx
- packages/web-app/src/Store.ts
- packages/web-app/src/modules/earn-views/components/EarningChart.tsx
Removes references to app_salad_bowl feature flag in the alpha branch
> [App] Remove outdated feature flags (alpha branch)

- packages/web-app/src/Store.ts
- packages/web-app/src/modules/zendesk/Zendesk.ts
missed the `app_helpscout` flag when i was removing feature flags earlier this week.
> [App] Removed app_helpscout flag

- packages/web-app/src/modules/earn-views/components/EarningChart.tsx
> [Bug] remove hi

- packages/web-app/src/modules/reward-views/components/RewardHeaderBar.tsx
- packages/web-app/src/modules/reward-views/components/RewardItem.tsx
- packages/web-app/src/modules/reward/models/Reward.ts
- packages/web-app/src/modules/reward/models/RewardResource.ts
- packages/web-app/src/modules/reward/models/SearchResult.ts
- packages/web-app/src/modules/reward/utils.ts
- packages/web-app/src/modules/storefront-views/blocks/StorefrontHeroBlock.tsx
- packages/web-app/src/modules/storefront-views/blocks/StorefrontRewardBlock.tsx
- packages/web-app/src/modules/storefront-views/components/StorefrontHeroItem.tsx
- packages/web-app/src/modules/storefront-views/components/StorefrontRewardItem.tsx
- packages/web-app/src/modules/storefront/models/StorefrontRewardItemProps.ts
Adds discount labels to our storefront. 
Hero Item:
Top Chops: 
Reward Details Page:
Search Results:
> [App] Master Branch Discount labels in store

- packages/web-app/src/modules/reward-views/components/RewardHeaderBar.tsx
- packages/web-app/src/modules/reward-views/components/RewardItem.tsx
- packages/web-app/src/modules/reward/models/Reward.ts
- packages/web-app/src/modules/reward/models/RewardResource.ts
- packages/web-app/src/modules/reward/models/SearchResult.ts
- packages/web-app/src/modules/reward/utils.ts
- packages/web-app/src/modules/storefront-views/blocks/StorefrontHeroBlock.tsx
- packages/web-app/src/modules/storefront-views/blocks/StorefrontRewardBlock.tsx
- packages/web-app/src/modules/storefront-views/components/StorefrontHeroItem.tsx
- packages/web-app/src/modules/storefront-views/components/StorefrontRewardItem.tsx
- packages/web-app/src/modules/storefront/models/StorefrontRewardItemProps.ts
Adds discount labels to our storefront for our alpha branch. 
Hero Item:
Top Chops: 
Reward Details Page:
Search Results:
> [App] Alpha branch discount labels

- packages/web-app/src/modules/reward-views/components/RewardHeaderBar.tsx
-fix reward price decimal point
> [App] Fix reward price decimal point

- packages/web-app/src/modules/reward-views/components/RewardHeaderBar.tsx
-fix reward price decimal point
> [App] Alpha fix price decimal on reward page

- packages/web-app/src/Store.ts
- packages/web-app/src/modules/helpscout/HelpScoutStore.tsx
- packages/web-app/src/modules/helpscout/models/HelpScout.tsx
- packages/web-app/src/modules/helpscout/models/interfaces.ts
- packages/web-app/src/modules/reward/RewardStore.ts
project - https://www.notion.so/saladtech/Helpscout-Beacon-NPS-Targeting-1dd0a27e51714f6495599195886b252f
task - https://www.notion.so/saladtech/App-Add-lifetimeXP-to-Beacon-API-83ac94197ee0485dbfc4e7cf0baa68a0
> [App] Add lifetimeXP to HelpScout beacon API

- packages/web-app/src/Store.ts
- packages/web-app/src/modules/auth/AuthStore.ts
- packages/web-app/src/modules/terms-and-conditions/TermsAndConditionsStore.ts
project - https://www.notion.so/saladtech/Terms-Conditions-Update-Flow-565e181573ff4068bc7aa5881a798534
task - https://www.notion.so/saladtech/App-Add-login-register-update-users-last-seen-terms-e90af1576e874adb828e691200beee6a
> [App] Add users last seen t&c's version update to login flow

- packages/web-app/src/Store.ts
- packages/web-app/src/modules/reward/RewardStore.ts
- packages/web-app/src/modules/zendesk/Zendesk.ts
- packages/web-app/src/modules/zendesk/models/ZendeskWebWidget.ts
**Description** - Add lifetime xp to zendesk Beacon api
**Notion Project** - https://www.notion.so/saladtech/Helpscout-Beacon-NPS-Targeting-1dd0a27e51714f6495599195886b252f
**Notion Task** - https://www.notion.so/saladtech/App-alpha-Add-lifetimeXP-changes-to-alpha-branch-e754dcc00401494aaf45b0b110f44d60
> [App- alpha] Add lifetime xp to zendesk Beacon api

- packages/web-app/src/components/UpgradePage.tsx
- packages/web-app/src/index.tsx
- packages/web-app/src/indexDeprecated.tsx
https://www.notion.so/saladtech/Disable-and-redirect-legacy-app-users-ca96c55783cb4fc7b7b8951bf059e43c?pvs=4
https://www.figma.com/file/IV8bjY0Oe393t8c0EWizk8/Product-Designs?node-id=6212%3A56683&t=aV78t11KKPg5X13B-4
> Disable and redirect legacy app users alpha

- packages/web-app/.env.development
- packages/web-app/.netlify/build.sh
- packages/web-app/src/modules/terms-and-conditions/TermsAndConditionsStore.ts
This migrates the testing environment web app builds from the API server on salad.io to salad.com. 🥗
> Migrate testing environment builds to .com

- packages/web-app/package.json
- packages/web-app/src/modules/home-views/NavigationBarContainer.tsx
- packages/web-app/yarn.lock
**Description:** remove isNative
**Issue:** https://www.notion.so/saladtech/Task-Board-0a1597db0965406fa64e2b5628077e21
> [App] Remove isNative 

- packages/web-app/.env
- packages/web-app/.env.development
- packages/web-app/package.json
- packages/web-app/src/components/NovuProviderWrapper/NovuProviderWrapper.tsx
- packages/web-app/src/components/NovuProviderWrapper/index.ts
- packages/web-app/src/config.tsx
- packages/web-app/src/index.tsx
- packages/web-app/yarn.lock
https://www.notion.so/saladtech/App-Receive-Notifications-from-Novu-in-the-Web-App-0c78de7b514949e0ab42e11338f33668?pvs=4
> [Web App] novu functionalilty to received push notification - added

- packages/web-app/src/App.tsx
- packages/web-app/src/modules/home-views/NavigationBarContainer.tsx
- packages/web-app/src/modules/home-views/components/NavigationBarWithNotifications.tsx
**Description:** Change novu initialization logic to be initialized only when novu signature was obtained
**Notion Task:** https://www.notion.so/saladtech/App-Add-novu-hmac-signature-8194f4321f6c44c390d27cf7a66d840a
**Notion Project:** https://www.notion.so/saladtech/Frontend-Add-push-notifications-to-the-web-app-3a60520ff8d4485d85965b12fa1c2e84
> [Web-app] Update novu initialization logic

- packages/web-app/src/modules/reward/RewardStore.tsx
**Description:** Remove undefined rewards request
**Notion Defect:** https://www.notion.so/saladtech/Store-Makes-Calls-To-An-Undefined-Reward-ed09e3065ecd4d1c948ab9af5f3e303b
> [Web-app] Remove undefined rewards request

- packages/web-app/src/modules/notifications/utils.tsx
**Description:** Add novu notifications special characters decoding
**Notion Defect:** https://www.notion.so/saladtech/Notification-Blast-Errors-cbecd6e648f64dfdb1534152531a9911
> [Web-app] Add novu notifications special characters decoding

- packages/web-app/.azure-pipelines/build.ps1
https://www.notion.so/saladtech/WebApp-Build-Develop-Text-in-Production-build-0946329be80e42828bf00efedf7cbb35?pvs=4
> [WebApp] REACT_APP_BUILD set to commit hash for production builds 

- packages/web-app/src/axiosFactory.tsx
- packages/web-app/src/modules/auth/AuthStore.tsx
**Description:** Handle lost session in Response interceptor
**Notion Task:** https://www.notion.so/saladtech/Handle-lost-session-in-Response-interceptor-003c456ff2fd427fb5b177c99e349968
> [WebApp] Handle lost session 

- packages/web-app/src/axiosFactory.tsx
- packages/web-app/src/modules/auth/AuthStore.tsx
Reverting unnecessary logging and functionality of switching between Identity Framework auth and SuperTokens auth
> [WebApp] logs and switching between auth methods - removed

- packages/web-app/src/modules/reward-views/pages/RewardDetailsPage/ReviewAfterRedemption/ReviewAfterRedemption.tsx
**Description:** Fix Share Review Redemption Pop-Up Spelling Error
**Notion Task:** https://www.notion.so/saladtech/Fix-Share-Review-Redemption-Pop-Up-Spelling-Error-0d49d54ee5d64394937e3cddc2a6930c
**Notion Defect:** https://www.notion.so/saladtech/Frontend-Share-Review-Redemption-Pop-Up-Spelling-Error-37aa143038f94d79be4a511f3974bdb1
> [Web-app] Fix Share Review Redemption Pop-Up Spelling Error

- packages/web-app/package.json
- packages/web-app/src/axiosFactory.tsx
- packages/web-app/src/modules/auth/AuthStore.tsx
- packages/web-app/src/modules/profile/ProfileStore.tsx
- packages/web-app/yarn.lock
**Description:** Remove supertokens
**Notion Task:** https://www.notion.so/saladtech/Web-App-remove-SuperTokens-2992c392035c405194b6e56cb527ba19
> [Web-App] Remove supertokens

- packages/web-app/src/modules/analytics/AnalyticsStore.tsx
**Description:** Remove rid header from mixpanel events
**Notion Task:** https://www.notion.so/saladtech/Remove-rid-header-5b39bee6d07445d1bd8636c2649625ae
> [Web-App] Remove rid header from mixpanel events

- packages/web-app/src/axiosFactory.tsx
https://www.notion.so/saladtech/Update-Web-App-9a72b98d1ff14daaa65331adef6de74d?pvs=4
> [WebApp] x-xsrf-token header - added to all requests made with axios

- packages/web-app/package.json
- packages/web-app/src/modules/home-views/components/NavigationBarWithNovuNotifications.tsx
- packages/web-app/src/modules/notifications/models/NotificationMessage.tsx
- packages/web-app/src/modules/notifications/utils.tsx
- packages/web-app/yarn.lock
https://www.notion.so/saladtech/Web-App-Alerts-add-Achievements-section-39014acddb3b46d4b90e5669c5d57b57?pvs=4
> [WebApp] Achievements notifications

- packages/web-app/package.json
- packages/web-app/src/FeatureManager.tsx
- packages/web-app/src/components/SettingsPage.tsx
- packages/web-app/src/modules/home-views/NavigationBarContainer.tsx
- packages/web-app/src/modules/home-views/components/NavigationBarWithNotifications.tsx
- packages/web-app/src/modules/home-views/components/NavigationBarWithNovuNotifications.tsx
- packages/web-app/src/modules/settings-views/SettingsContainer.tsx
- packages/web-app/yarn.lock
https://www.notion.so/saladtech/WebApp-Add-Unleash-flag-91cd8a956aa54cbf9ad50dba9c048ac2?pvs=4
> [WebApp] Achievements: feature flag condition - added

- packages/web-app/.env
prod REACT_APP_NOVU_APP_ID temporary changed to the Dev value
> [WebApp] prod REACT_APP_NOVU_APP_ID temporary changed to the Dev value

- packages/web-app/.env
`REACT_APP_NOVU_APP_ID` changed to prod value in `.env`
> [WebApp] Revert "prod REACT_APP_NOVU_APP_ID temporary changed to the Dev value"

- packages/web-app/.env
- packages/web-app/.env.development
- packages/web-app/src/config.tsx
- packages/web-app/src/modules/auth/AuthStore.tsx
**Description:**   Fix redirect to login
**Notion Task:** https://www.notion.so/saladtech/App-Remove-the-login-from-web-app-5b8064fdff384be5a6c6ad52d1db2af2
**Notion Project:** https://www.notion.so/saladtech/Frontend-Remove-web-app-login-pages-e7159a0e89fb4da9a05e17deda7049f5
> [WebApp] Fix redirect for login

- packages/web-app/.env
**Description:**   Change env login link for Demo remove login functionality
**Notion Task:** https://www.notion.so/saladtech/App-Remove-the-login-from-web-app-5b8064fdff384be5a6c6ad52d1db2af2
**Notion Project:** https://www.notion.so/saladtech/Frontend-Remove-web-app-login-pages-e7159a0e89fb4da9a05e17deda7049f5
> [WebApp]  Change env login link for Demo remove login functionality

- packages/web-app/.env
**Description:**  Revert login redirect link for prod
**Notion Task:** https://www.notion.so/saladtech/App-Remove-the-login-from-web-app-5b8064fdff384be5a6c6ad52d1db2af2
**Notion Project:** https://www.notion.so/saladtech/Frontend-Remove-web-app-login-pages-e7159a0e89fb4da9a05e17deda7049f5
> [WebApp] Revert login redirect link for prod

- packages/web-app/.azure-pipelines/build.ps1
**Description:**  Configure new env variables for testing env
**Notion Project:** https://www.notion.so/saladtech/Frontend-Remove-web-app-login-pages-e7159a0e89fb4da9a05e17deda7049f5
> [WebApp] Configure new env variables for testing env

- packages/web-app/src/Store.tsx
- packages/web-app/src/modules/achievements-views/AchievementPageContainer.tsx
- packages/web-app/src/modules/achievements-views/components/AchievementPage.tsx
- packages/web-app/src/modules/achievements/AchievementsStore.tsx
- packages/web-app/src/modules/achievements/index.tsx
- packages/web-app/src/modules/achievements/models/Achievement.ts
https://www.notion.so/saladtech/WebApp-Connect-Achievement-Page-eb83f41b7b724255a8685442c091cc9e?pvs=4
> [WebApp] Achievements Page - connected

- packages/web-app/src/modules/achievements-views/components/AchievementCard.tsx
> [WebApp] AchievementCard: dateAchievedFormatted - added

- packages/web-app/src/App.tsx
- packages/web-app/src/modules/home-views/NavigationBarContainer.tsx
- packages/web-app/src/modules/profile/ProfileStore.tsx
> [WebApp] Top space for page content 

- packages/web-app/src/modules/auth/AuthStore.tsx
https://www.notion.so/saladtech/Refactor-login-redirect-param-to-generic-redirect_uri-and-set-default-redirect-to-store-6c2037db5afb4821b637762e2a446e90
> [Web] Refactor login redirect param to generic redirect_uri

- packages/web-app/src/App.tsx
> [WebApp] search - fixed

- packages/web-app/src/config.tsx
- packages/web-app/src/modules/account-views/account-views/components/Account.tsx
- packages/web-app/src/modules/profile/ProfileStore.tsx
https://www.notion.so/saladtech/Enable-SSO-only-in-test-env-4afda440f98a4ecdb3d398fece55d093
> [WebApp] Enable google sso in test env

- packages/web-app/src/components/Dropdown.tsx
https://www.notion.so/saladtech/WebApp-Search-sort-value-label-revert-issue-073712e0a784486fbdaddbcec51d336d
> [WebApp] Fix search sort value revert issue

- packages/web-app/src/modules/account-views/account-views/components/Account.tsx
- packages/web-app/src/modules/profile/ProfileStore.tsx
**Description:** Remove hiding google sso
**Issue:** https://www.notion.so/saladtech/Enable-Google-button-in-Prod-baf2223ea93f47a8b6075347d85d8691?pvs=23
> [WebApp] Remove hiding google sso

- packages/web-app/src/modules/account-views/account-views/components/Account.tsx
- packages/web-app/src/modules/profile/ProfileStore.tsx
Reverts SaladTechnologies/salad-applications#1125
> Revert "[WebApp] Remove hiding google sso"

- packages/web-app/src/modules/home-views/components/NavigationBarWithNovuNotifications.tsx
**Description:** Update star chef filter to avoid an error with old notifications
> [WebApp] update star chef filter

- packages/web-app/src/modules/home-views/components/NavigationBarWithNovuNotifications.tsx
Fix notifications infinite request loop defect
> [Web-app] Fix notifications infinite request loop

- packages/web-app/package.json
- packages/web-app/yarn.lock
https://www.notion.so/saladtech/WebApp-Notification-Dismiss-button-loader-2a9b653fe3b142aa80b41d26db52fa64?pvs=4
> [WebApp] @saladtechnologies/garden-components: version - updated

- packages/web-app/src/Routes.tsx
https://www.notion.so/saladtech/WebApp-Add-exit-survey-redirect-functionality-82d130ca5df144b3904f2352cc873eb0?pvs=4
> [WebApp] Route account/exit-survey - added

- packages/web-app/src/modules/earn-views/components/EarningChart.tsx
https://www.notion.so/saladtech/Add-Earnings-Per-Machin-toggle-fb3b74100b94456eb547b1cc47473b17?pvs=4
> [WebApp] EarningChart: Earnings Per Machine Switch - added

- packages/web-app/src/modules/balance/BalanceStore.tsx
- packages/web-app/src/modules/balance/models/EarningWindow.tsx
- packages/web-app/src/modules/earn-views/EarningLineChartContainer.tsx
- packages/web-app/src/modules/earn-views/components/EarningChart.tsx
- packages/web-app/src/modules/earn-views/components/EarningLineChart.tsx
- packages/web-app/src/modules/earn-views/components/EarningLineChart/EarningLineChart.tsx
- packages/web-app/src/modules/earn-views/components/EarningLineChart/components/CustomizedXAxisTick.tsx
- packages/web-app/src/modules/earn-views/components/EarningLineChart/components/index.tsx
- packages/web-app/src/modules/earn-views/components/EarningLineChart/index.tsx
- packages/web-app/src/modules/earn-views/components/index.tsx
- packages/web-app/src/modules/earn-views/pages/constants.tsx
- packages/web-app/src/modules/earn-views/utils.tsx
**Description:** Create earning line chart
**Issue:** https://www.notion.so/saladtech/Create-new-line-chart-for-multiple-IDs-5219629c3455462fb62f081f7e844d29
> [WebApp] Create earning line chart

- packages/web-app/src/modules/earn-views/components/EarningHistory.tsx
https://www.notion.so/saladtech/Update-Create-functionality-for-retrieving-data-from-API-call-based-on-Backend-progress-7d3d6058cc4942308f6baf1a18c0036f?pvs=4
> [WebApp] EarningsPerMachine Chart: description - added

- packages/web-app/src/modules/earn-views-mobile/MobileEarningSummaryContainer.tsx
- packages/web-app/src/modules/earn-views-mobile/components/MobileEarningSummary.tsx
**Description:** Add charts to mobile view
> [WebApp] Add charts to mobile view

- packages/web-app/src/modules/account-views/referral-views/CurrentReferralPanelContainer.tsx
- packages/web-app/src/modules/account-views/referral-views/ReferralSettingsContainer.tsx
- packages/web-app/src/modules/account-views/referral-views/components/CurrentReferralPanel.tsx
- packages/web-app/src/modules/account-views/referral-views/components/ReferralSettings.tsx
**Description:** Update referral progress section
> [WebApp] Update referral progress section

- packages/web-app/src/components/SettingsPage.tsx
- packages/web-app/src/modules/home-views/NavigationBarContainer.tsx
- packages/web-app/src/modules/home-views/components/NavigationBarWithNotifications.tsx
- packages/web-app/src/modules/referral/ReferralStore.tsx
- packages/web-app/src/modules/settings-views/SettingsContainer.tsx
https://www.notion.so/saladtech/WebApp-When-user-referral-system-off-in-the-web-app-disable-the-Referrals-section-5d8b019e4493457285832f419d8cb28e?pvs=4
> [WebApp] disabling Referrals Page based on Support Tool settings - added

- packages/web-app/src/Routes.tsx
- packages/web-app/src/modules/passkey-setup/PasskeySetupPageContainer.tsx
- packages/web-app/src/modules/passkey-setup/components/PasskeySetupPage.tsx
- packages/web-app/src/modules/passkey-setup/components/assets/Referrals.svg
- packages/web-app/src/modules/passkey-setup/components/index.tsx
- packages/web-app/src/modules/passkey-setup/index.tsx
**Description:** Add passkey setup page
**Issue:** https://www.notion.so/saladtech/FE-Web-app-Passkey-Setup-UI-only-598bfa23611f48b3afbf27cf31fad200
> [WebApp] Add passkey setup page

- packages/web-app/src/modules/account-views/account-views/components/Account.tsx
- packages/web-app/src/modules/account-views/account-views/components/AccountSecurity.tsx
https://www.notion.so/saladtech/FE-Web-app-Profile-Page-add-a-new-section-called-Account-Security-UI-only-b214c20882a54198acfaf27b4540c535?pvs=4
> [WebApp] Profile: AccountSecurity section - added

- packages/web-app/src/Store.tsx
- packages/web-app/src/hooks.ts
- packages/web-app/src/modules/passkey-setup/PasskeySetupPageContainer.tsx
- packages/web-app/src/modules/passkey-setup/PasskeyStore.tsx
- packages/web-app/src/modules/passkey-setup/components/PasskeySetupPage.tsx
- packages/web-app/src/modules/passkey-setup/index.tsx
- packages/web-app/src/modules/passkey-setup/utils.ts
**Description:** Add passkey support logic
**Issue:** https://www.notion.so/saladtech/FE-Web-app-Passkey-support-logic-ecedbebec44d43eebdbb883a9ed08c01
> [WebApp] Add passkey support logic

- packages/web-app/src/Routes.tsx
- packages/web-app/src/modules/reward-views/pages/RewardDetailsPage/ReviewAfterRedemption/ReviewAfterRedemption.tsx
- packages/web-app/src/modules/reward-views/pages/RewardDetailsPage/ReviewAfterRedemption/ReviewAfterRedemptionContainer.tsx
**Description:** Remove referral code in redemption popup
**Issue:** https://www.notion.so/saladtech/Remove-referral-code-in-popup-72c3a6bb07034c56b7d08e67bd4b7ada
> [WebApp] Remove referral code in redemption popup

- packages/web-app/src/modules/reward-views/pages/RewardDetailsPage/ReviewAfterRedemption/ReviewAfterRedemption.tsx
**Description:** Update redemption popup description
**Issue:** https://www.notion.so/saladtech/Update-redemption-popup-description-b727972921564766ae4ebf7b620e5849
> [WebApp] Update redemption popup description

- packages/web-app/src/Routes.tsx
- packages/web-app/src/Store.tsx
- packages/web-app/src/components/TextField.tsx
- packages/web-app/src/components/primitives/content/ErrorText.tsx
- packages/web-app/src/modules/account-views/account-views/AccountContainer.tsx
- packages/web-app/src/modules/account-views/account-views/components/Account.tsx
- packages/web-app/src/modules/account-views/account-views/components/AccountSecurity.tsx
- packages/web-app/src/modules/passkey-setup/PasskeySetupPageContainer.tsx
- packages/web-app/src/modules/passkey-setup/PasskeyStore.tsx
- packages/web-app/src/modules/passkey-setup/components/PasskeySetupPage.tsx
- packages/web-app/src/modules/passkey-setup/utils.ts
- packages/web-app/src/modules/passkey-success/PasskeySuccessPageContainer.tsx
- packages/web-app/src/modules/passkey-success/components/PasskeySuccessPage.tsx
https://www.notion.so/saladtech/FE-Integrate-Passkey-endpoints-create-passkey-and-sign-in-bbc10f87b7634532918029b903c2f8ab?pvs=4
https://www.notion.so/saladtech/FE-Integrate-Passkey-endpoints-get-passkeys-and-delete-passkey-26c3fb5950fa469981e60099404b2447?pvs=4
> [WebApp] passkey integration - added

- packages/web-app/src/modules/account-views/account-views/components/AccountSecurity.tsx
https://www.notion.so/saladtech/FE-Add-passkey-limit-of-30-9cd6b9521fe54017adf9cc969f38d2b1?pvs=4
> [WebApp] Passkey amount limit

- packages/web-app/src/modules/analytics/AnalyticsStore.tsx
- packages/web-app/src/modules/passkey-setup/PasskeyStore.tsx
https://www.notion.so/saladtech/FE-WebApp-Mixpanel-Event-Tracking-3272de539dfd47f0adb22831e5f2bb21?pvs=4
> [WebApp] Mixpanel trackPasskeyAdded - added

- packages/web-app/src/modules/passkey-setup/components/PasskeySetupPage.tsx
- packages/web-app/src/modules/passkey-setup/components/utils.ts
https://www.notion.so/saladtech/FE-Add-default-passkey-name-generating-functionality-84f0c3e25da14816aa2dcb69b08ca809?pvs=4
> [WebApp] Generate default passkey name

- packages/web-app/src/components/primitives/content/ErrorText.tsx
- packages/web-app/src/modules/passkey-setup/PasskeySetupPageContainer.tsx
- packages/web-app/src/modules/passkey-setup/PasskeyStore.tsx
- packages/web-app/src/modules/passkey-setup/components/PasskeySetupPage.tsx
https://www.notion.so/saladtech/FE-Add-Passkey-error-handling-125d35393a7a4f9787e1bbe8bfa07bad?pvs=4
> [WebApp] Add passkey error handling

- packages/web-app/src/Routes.tsx
- packages/web-app/src/modules/account-views/account-views/AccountContainer.tsx
- packages/web-app/src/modules/passkey-delete/PasskeyDeletePageContainer.tsx
- packages/web-app/src/modules/passkey-delete/components/PasskeyDeletePage.tsx
- packages/web-app/src/modules/passkey-delete/components/index.tsx
- packages/web-app/src/modules/passkey-delete/index.tsx
- packages/web-app/src/modules/passkey-setup/PasskeyStore.tsx
**Description:** Add passkey delete confirmation screen
**Issue:** https://www.notion.so/saladtech/FE-Delete-Passkey-Confirmation-UI-e8c8ef4fff424d458fec25d1e348a604
> [WebApp] Add passkey delete confirmation screen

- packages/web-app/src/modules/passkey-setup/PasskeyStore.tsx
Feature Enabled 
https://www.notion.so/saladtech/Backend-Frontend-Kitchen-Passkeys-as-login-method-1d19645dfd0a4555b851595766382361?pvs=4
> [WebApp] Passkey feature - enabled

- packages/web-app/src/components/DeviceTypes.tsx
- packages/web-app/src/modules/account-views-mobile/MobileAccountSummaryContainer.tsx
- packages/web-app/src/modules/account-views-mobile/components/MobileAccountSummary.tsx
- packages/web-app/src/modules/account-views/account-views/AccountContainer.tsx
- packages/web-app/src/modules/account-views/account-views/AccountSecurityContainer.tsx
- packages/web-app/src/modules/account-views/account-views/components/Account.tsx
- packages/web-app/src/modules/account-views/account-views/components/AccountSecurity.tsx
- packages/web-app/src/modules/account-views/account-views/index.tsx
**Description:** Add account security mobile view
**Issue:** https://www.notion.so/saladtech/FE-Add-account-security-mobile-view-9f2ba3af3d9a4cbfb3e44ad63c125463
> [WebApp] Add account security mobile view

- packages/web-app/src/MobileRoutes.tsx
- packages/web-app/src/components/TextField.tsx
- packages/web-app/src/modules/account-views/account-views/components/EditUsername.tsx
- packages/web-app/src/modules/account-views/account-views/components/MinecraftUsername.tsx
- packages/web-app/src/modules/account-views/referral-views/components/SendReferral.tsx
- packages/web-app/src/modules/passkey-delete/components/PasskeyDeletePage.tsx
- packages/web-app/src/modules/passkey-setup/components/PasskeySetupPage.tsx
- packages/web-app/src/modules/passkey-success/components/PasskeySuccessPage.tsx
https://www.notion.so/saladtech/FE-Passkeys-Pages-mobile-layots-34cfa6a0e0334e2b93346fd6f377d5aa?pvs=4
> [WebApp] Passkeys mobile pages

- packages/web-app/src/modules/account-views/account-views/components/AccountSecurity.tsx
https://www.notion.so/saladtech/FE-Passkeys-amount-UI-827d82bf95d24c14875897d8c1748822?pvs=4
> [WebApp] passkeys amount ui - added

- packages/web-app/src/modules/passkey-setup/components/utils.ts
https://www.notion.so/saladtech/FE-Add-default-passkey-name-generating-functionality-84f0c3e25da14816aa2dcb69b08ca809?pvs=4
> [WebApp] android OS detection - fixed

- packages/web-app/src/modules/passkey-delete/components/PasskeyDeletePage.tsx
**Description:** Fix remove passkey button icon
> [WebApp] Fix remove passkey button icon

- packages/web-app/src/Routes.tsx
- packages/web-app/src/modules/protected-action/ProtectedActionPageContainer.tsx
- packages/web-app/src/modules/protected-action/components/ProtectedActionPage.tsx
- packages/web-app/src/modules/protected-action/components/index.tsx
- packages/web-app/src/modules/protected-action/index.tsx
**Description:** Add protected action page
**Issue:** https://www.notion.so/saladtech/Protected-Action-page-3a516fccc3474ceea00c92847e950ce9
> [WebApp] Add protected action page

- packages/web-app/src/modules/account-views/account-views/AccountSecurityContainer.tsx
- packages/web-app/src/modules/account-views/account-views/components/AccountSecurity.tsx
https://www.notion.so/saladtech/Add-Backup-Codes-section-d173e7d1e56247c8bc2f12eed1508c75?pvs=4
> [WebApp] backup codes section - added

- packages/web-app/src/Store.tsx
- packages/web-app/src/modules/backup-codes/BackupCodesStore.tsx
- packages/web-app/src/modules/backup-codes/index.tsx
- packages/web-app/src/modules/passkey-setup/PasskeyStore.tsx
- packages/web-app/src/modules/passkey-setup/utils.ts
- packages/web-app/src/modules/protected-action/ProtectedActionPageContainer.tsx
- packages/web-app/src/modules/protected-action/components/ProtectedActionPage.tsx
**Description:** Add protected action endpoints
**Issue:** https://www.notion.so/saladtech/Protected-Action-endpoints-integration-31c9d541d84a42c6ac63eec90dad4fc1
> [WebApp] Add protected action endpoints

- packages/web-app/src/modules/backup-codes/components/BackupCodesPage.tsx
https://www.notion.so/saladtech/The-Backup-Codes-page-042fc2d4ec2343f3b4040651076dadfb?pvs=4
> [WebApp] backup codes are selectable

- packages/web-app/src/components/primitives/content/ErrorText.tsx
- packages/web-app/src/components/primitives/content/SuccessText.tsx
- packages/web-app/src/modules/account-views/account-views/AccountSecurityContainer.tsx
- packages/web-app/src/modules/account-views/account-views/components/AccountSecurity.tsx
- packages/web-app/src/modules/passkey-setup/PasskeyStore.tsx
https://www.notion.so/saladtech/FE-Change-UI-for-Passkeys-Adding-labels-instead-of-pages-f585d3eb436b4ecabf67c322ea15fac6?pvs=4
> [WebApp] add passkey result labels - added

- packages/web-app/src/modules/backup-codes/components/BackupCodesPage.tsx
https://www.notion.so/saladtech/The-Backup-Codes-page-042fc2d4ec2343f3b4040651076dadfb?pvs=4
> [WebApp] BackupCodesPage: COPY button - added

- packages/web-app/src/modules/backup-codes/components/BackupCodesPage.tsx
Backup codes date - moved to another line
> [WebApp] BackupCodesPage: layouts - improved

- packages/web-app/src/modules/account-views/account-views/components/AccountSecurity.tsx
**Description:** Add tooltip for passkey names
> [WebApp] Add tooltip for passkey names

- packages/web-app/src/MobileRoutes.tsx
- packages/web-app/src/Routes.tsx
- packages/web-app/src/modules/account-views-mobile/components/MobileAccountSummary.tsx
- packages/web-app/src/modules/account-views/account-views/components/Account.tsx
- packages/web-app/src/modules/backup-codes/BackupCodesStore.tsx
- packages/web-app/src/modules/passkey-setup/PasskeyStore.tsx
**Description:** Remove isPasskeyFeatureEnabled flag
> [WebApp] Remove isPasskeyFeatureEnabled flag

- packages/web-app/src/modules/account-views/account-views/AccountSecurityContainer.tsx
- packages/web-app/src/modules/account-views/account-views/components/AccountSecurity.tsx
https://www.notion.so/saladtech/FE-Add-Protected-Action-sub-section-UI-only-9013a007488948da84d9ded2c3dfda44?pvs=4
> [WebApp] Protected Actions section - added

- packages/web-app/src/modules/passkey-setup/PasskeyStore.tsx
- packages/web-app/src/modules/passkey-setup/utils.ts
**Description:** Fix proton pass password manager issue using not null value for displayName
> [WebApp] Fix proton pass password manager issue

- packages/web-app/src/modules/auth/AuthStore.tsx
- packages/web-app/src/modules/protected-action/utils.tsx
- packages/web-app/src/modules/reward/RewardStore.tsx
- packages/web-app/src/modules/salad-pay-views/SaladPayOrderSummaryContainer.tsx
- packages/web-app/src/modules/salad-pay-views/components/SaladPayOrderSummaryPage.tsx
- packages/web-app/src/modules/salad-pay/SaladPayStore.tsx
**Description:** Challenge sudo mode on Reward Page BUY button click
**Issue:** https://www.notion.so/saladtech/FE-Challenge-sudo-mode-on-Reward-Page-BUY-button-click-6f1a7b449028447c9d12ff5a07860d59
> [WebApp] Challenge sudo mode on Reward Page BUY button click

- packages/web-app/src/axiosFactory.tsx
- packages/web-app/src/modules/account-views/account-views/AccountSecurityContainer.tsx
- packages/web-app/src/modules/account-views/account-views/components/AccountSecurity.tsx
- packages/web-app/src/modules/auth/AuthStore.tsx
- packages/web-app/src/modules/profile/ProfileStore.tsx
- packages/web-app/src/modules/profile/constants.tsx
- packages/web-app/src/modules/profile/models/Profile.tsx
- packages/web-app/src/modules/protected-action/utils.tsx
- packages/web-app/src/modules/reward/RewardStore.tsx
**Description:** Connect protect reward redemption
> [SALAD-21537] [WebApp] Connect protect reward redemption

- packages/web-app/src/modules/analytics/AnalyticsStore.tsx
- packages/web-app/src/modules/exit-survey-views/ExitSurveyContainer.tsx
- packages/web-app/src/modules/exit-survey-views/components/ExitSurvey.tsx
https://www.notion.so/saladtech/Track-Uninstall-Mixpanel-Event-a388b6ae908f405d943c3060cee8b9d2?pvs=4
> [WebApp] Uninstall event tracking - added

- packages/web-app/src/modules/notifications/models/NotificationMessage.tsx
- packages/web-app/src/modules/profile/ProfileStore.tsx
- packages/web-app/src/modules/profile/constants.tsx
**Description:**  Add paypal notification
> [SALAD-21966] WebApp - Add paypal notification

- packages/web-app/src/modules/exit-survey-views/components/ExitSurvey.tsx
**Description:** Fix exit form
> WebApp - Fix exit form

- packages/web-app/public/index.html
- packages/web-app/src/hooks/useAddOgMetaTags.tsx
- packages/web-app/src/modules/storefront-views/pages/StorefrontPage.tsx
**Description:** Add default preview
> WebApp - Add default preview

- packages/web-app/src/modules/protected-action/components/ProtectedActionPage.tsx
**Description:** Add a link to a guide in protected action page
> [SALAD-22627] WebApp - Add a link to a guide in protected action page

- packages/web-app/src/FeatureManager.tsx
- packages/web-app/src/MobileRoutes.tsx
- packages/web-app/src/Routes.tsx
**Description:** Add feature flag for demand monitor
> [SALAD-22779] WebApp - Add feature flag for demand monitor

- packages/web-app/public/index.html
**Description:** Add description meta tag
> [SALAD-22879] WebApp - Add description meta tag

- packages/web-app/public/index.html
**Description:** Fix description meta tag
> WebApp - Fix description meta tag

- packages/web-app/src/modules/storefront-views/blocks/StorefrontCommunityChallengeBlock.tsx
**Description:** Fix storefront report
> WebApp - Fix storefront report

- packages/web-app/src/modules/demand-alerts-views/DemandAlertsPage/DemandAlertsPage.tsx
- packages/web-app/src/modules/demand-alerts-views/DemandAlertsPage/DemandAlertsSetUp/DemandAlertsSetUp.tsx
**Description:** Add content to demand alerts page
> [WebApp] Add content to demand alerts page

- packages/web-app/src/components/ModalWithOverlay/ModalWithOverlay.tsx
- packages/web-app/src/modules/demand-monitor-views/DemandMonitorPage/GetNotifiedDemandChangesModal/GetNotifiedDemandChangesModal.tsx
> [SALAD-23180] WebApp: Mobile UI for demand notification modals

- packages/web-app/src/modules/auth/AuthStore.tsx
- packages/web-app/src/modules/demand-monitor-views/DemandMonitorPage/DemandMonitorPageContainer.tsx
**Description:** Redirect to Demand Alerts Page on successful login
> [SALAD-23183] WebApp - Redirect to Demand Alerts Page on successful login

- packages/web-app/package.json
- packages/web-app/src/modules/demand-monitor-views/DemandMonitorPage/DemandMonitorTable/DemandMonitorTable.tsx
- packages/web-app/src/modules/demand-monitor-views/DemandMonitorPage/DemandMonitorTable/constants.ts
- packages/web-app/src/modules/demand-monitor-views/DemandMonitorPage/DemandMonitorTable/types.ts
- packages/web-app/src/modules/demand-monitor-views/DemandMonitorPage/DemandMonitorTable/utils.ts
- packages/web-app/src/modules/demand-monitor-views/DemandMonitorStore.tsx
- packages/web-app/yarn.lock
> [WebApp SALAD-23203] Replace average earning columns with only average earning rate for demand page table

- packages/web-app/src/App.tsx
- packages/web-app/src/Store.tsx
- packages/web-app/src/modules/analytics/AnalyticsStore.tsx
- packages/web-app/src/modules/analytics/util.ts
- packages/web-app/src/utils.tsx
**Description:** Add marketing touchpoint tracking
> [SALAD-23117] WebApp - Add marketing touchpoint tracking

- packages/web-app/src/modules/demand-monitor-views/DemandMonitorPage/DemandMonitorFAQ/DemandMonitorFAQ.tsx
**Description:** Update demand monitor FAQ with new text
> [SALAD-23392] WebApp - Update demand monitor FAQ with new text

- packages/web-app/src/modules/demand-monitor-views/DemandMonitorPage/DemandMonitorTable/DemandMonitorTable.tsx
**Description:** Flip the earning ranges around
> WebApp - Flip the earning ranges around

- packages/web-app/package.json
- packages/web-app/yarn.lock
**Description:**  Downgrade garden component version
> WebApp - Downgrade garden component version

- packages/web-app/package.json
- packages/web-app/yarn.lock
**Description:** Bump garden components version
> WebApp - Bump garden components version

- LICENSE
- packages/desktop-app-obliterator/obliterator.nsi
Happy New Year! This bumps the copyright year. We're excited for all that's to come in 2025!
> Bump copyright year

- packages/web-app/src/modules/demand-alerts-views/DemandAlertsPage/DemandAlertsList/DemandAlertsList.tsx
- packages/web-app/src/modules/demand-alerts-views/DemandAlertsPage/DemandAlertsPage.tsx
**Description:** Fix demand alerts list styles
> WebApp - Fix demand alerts list styles

- packages/web-app/src/modules/demand-alerts-views/DemandAlertsPage/DemandAlertsList/DemandAlertsList.tsx
- packages/web-app/src/modules/demand-alerts-views/DemandAlertsStore.tsx
**Description:** Sort demand alerts list
> WebApp - Sort demand alerts list

- packages/web-app/src/modules/demand-monitor-views/DemandMonitorPage/DemandMonitorTable/DemandMonitorTable.tsx
- packages/web-app/src/modules/demand-monitor-views/DemandMonitorStore.tsx
**Description:** Update sub-header with Super variant on demand page
> [SALAD-23992] WebApp - Update sub-header with Super variant on demand page

- packages/web-app/src/components/Pagination/Pagination.tsx
- packages/web-app/src/components/Pagination/index.ts
- packages/web-app/src/components/Pagination/usePagination.tsx
- packages/web-app/src/modules/earn-views/components/AllMachines/AllMachines.tsx
- packages/web-app/src/modules/earn-views/components/AllMachines/mocks.ts
> [SALAD-23960] WebApp: Pagination

- packages/web-app/src/modules/earn-views/components/EarningLineChart/EarningLineChart.tsx
- packages/web-app/src/modules/earn-views/components/EarningLineChart/components/EarningMachineList.tsx
**Description:** Make earning history section mobile adaptive
> [SALAD-24010] WebApp -Make earning history section mobile adaptive

- packages/web-app/src/modules/earn-views/components/AllMachines/AllMachines.tsx
- packages/web-app/src/modules/earn-views/components/AllMachines/mocks.ts
- packages/web-app/src/modules/earn-views/components/MachineDetailsModal/MachineDetailsModal.tsx
- packages/web-app/src/modules/earn-views/components/MachineDetailsModal/index.ts
- packages/web-app/src/modules/earn-views/pages/EarningSummaryPage.tsx
> [Web SALAD-23963] Add machine details modal

- packages/web-app/package.json
- packages/web-app/src/modules/analytics/AnalyticsStore.tsx
- packages/web-app/yarn.lock
This removes Hotjar from the Salad web app.
> Remove Hotjar

- packages/web-app/src/components/Dropdown/Dropdown.tsx
- packages/web-app/src/components/Dropdown/index.ts
- packages/web-app/src/components/Table/Table.tsx
- packages/web-app/src/modules/earn-views/components/AllMachines/AllMachines.tsx
- packages/web-app/src/modules/earn-views/pages/EarningSummaryPage.tsx
> [SALAD-24280] WebApp: Dropdown component

- packages/web-app/src/modules/earn-views-mobile/MobileEarningSummaryContainer.tsx
- packages/web-app/src/modules/earn-views-mobile/components/MobileEarningSummary.tsx
- packages/web-app/src/modules/earn-views/EarningSummaryContainer.tsx
- packages/web-app/src/modules/earn-views/components/AllMachines/mocks.ts
- packages/web-app/src/modules/earn-views/pages/EarningSummaryPage.tsx
**Description:** Connect line chart to All Machines selector
> WebApp - connect line chart to All Machines selector

- packages/web-app/src/components/Table/Table.tsx
- packages/web-app/src/modules/balance/BalanceStore.tsx
- packages/web-app/src/modules/earn-views/components/AllMachines/AllMachines.tsx
- packages/web-app/src/modules/earn-views/components/EarningHistory/EarningHistory.tsx
- packages/web-app/src/modules/earn-views/components/EarningTable/EarningTable.tsx
- packages/web-app/src/modules/earn-views/components/EarningTable/mocks.ts
> [SALAD-24284] WebApp: Earning history table views

- packages/web-app/src/modules/earn-views/components/EarningLineChart/utils.ts
**Description:** Fix aggregate earnings for chart function
> WebApp - Fix aggregate earnings for chart function

- packages/web-app/src/modules/earn-views/components/EarningHistory/EarningHistory.tsx
- packages/web-app/src/modules/earn-views/components/EarningHistory/constants.ts
- packages/web-app/src/modules/earn-views/components/EarningLineChart/EarningLineChart.tsx
- packages/web-app/src/modules/earn-views/components/EarningLineChart/constants.ts
**Description:** Fix disabling individual chart
> WebApp - Fix disabling individual chart

- packages/web-app/.azure-pipelines/deploy.ps1
**Description:** Renamed prod-if-unlocked cli argument
> Webapp - Renamed prod-if-unlocked cli argument

- packages/web-app/package.json
- packages/web-app/yarn.lock
**Description:** Update garden components version
> [SALAD-24551] WebApp - Update garden components version

- packages/web-app/src/modules/demand-monitor-views/DemandMonitorPage/DemandMonitorTable/DemandMonitorTable.tsx
**Description:** Flip the earning ranges back. Thanks to @FemboyNova for the contribution. The change is based on a suggestion from this [PR](https://github.com/SaladTechnologies/salad-applications/pull/1303).
> WebApp - Flip the earning ranges back

- packages/web-app/src/modules/demand-monitor-views/DemandMonitorPage/DemandMonitorTable/DemandMonitorTable.tsx
**Description:** Update copy on Salad Network Monitor page
> [SALAD-24654] WebApp - Update copy on Salad Network Monitor page

- packages/web-app/src/modules/earn-views/components/EarningFrequentlyAskedQuestions.tsx
Earning Summary FAQ links - updated
> [SALAD-24816] WebApp: Earning Summary links - updated

- packages/web-app/src/components/Pagination/Pagination.tsx
- packages/web-app/src/components/Table/Table.tsx
- packages/web-app/src/modules/earn-views/components/EarningHistory/EarningHistory.tsx
- packages/web-app/src/modules/earn-views/components/EarningTable/EarningTable.tsx
https://github.com/user-attachments/assets/189475e1-481e-4e91-a620-fda7a4b5a5e6
> [SALAD-24817] WebApp: Table scrollbars fix

- packages/web-app/src/components/Table/Table.tsx
- packages/web-app/src/index.css
**Description:** Fix the horizontal scrollbar problem in Firefox for the Earning History section, reverting to the default scrollbar.
> [SALAD-25212] WebApp - fix horizontal scrollbar in firefox

- packages/web-app/package.json
- packages/web-app/src/modules/home-views/components/NavigationBarWithNovuNotifications.tsx
- packages/web-app/yarn.lock
This should add a 'dismiss all' button to the sections of the notification drawer, which should mark all notifications in that category as seen and read when clicked.
> [Web-App] Added dismiss all button functionality
